# New ports collection makefile for:	ytalk
# Version required:	3.1
# Date created:		18 March 1995
# Whom:			dom@myrddin.demon.co.uk
#
# $Id$
#

DISTNAME=	ytalk-3.1
CATEGORIES=	net
MASTER_SITES=	http://www.eleves.ens.fr:8080/home/espel/ytalk/

MAINTAINER=	dom@myrddin.demon.co.uk

MAN1=		ytalk.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
