# New ports collection makefile for:	asedit
# Version required:			1.3.2
# Date created:				28 Jul 1996
#
# Whom:	Andreas Kohout <shanee@rabbit.augusta.de>
#
# $Id$
#

DISTNAME=	asedit-1.3.2
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_CONTRIB}
MASTER_SITE_SUBDIR=	editors
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	shanee@rabbit.augusta.de

REQUIRES_MOTIF=	yes
USE_IMAKE=	yes
XMKMF=		xmkmf

.include <bsd.port.mk>
