# $Id$
#
# RESTRICTED: pgp.usa_only (local restrections)
# RESTRICTED: pgp.non-usa_only (local restrictions)
# RESTRICTED: mmv (restrictive copyright)
#
# BROKEN: wine (doesn't install)
# BROKEN: vmsbackup (can't connect to ftp site)
#

SUBDIR= amanda chord colorls cpm hfs iozone ispell kp less lmbench \
	mshell mtools \
	pcemu rman screen top tua xbatt xdu xsysstats 

.include <bsd.port.subdir.mk>
