# $Id$
#
# restricted: pgp.usa_only pgp.non-usa_only 
#
# BROKEN: cpm (no MASTER_SITES) wine (doesn't install)
#

SUBDIR= amanda colorls hfs iozone ispell less mmv mshell mtools \
	pcemu rman screen top tua xdu xsysstats 

.include <bsd.port.subdir.mk>
