# $Id$
#

    SUBDIR += amanda
    SUBDIR += astrolog
    SUBDIR += buffer
    SUBDIR += chord
    SUBDIR += colorls
    SUBDIR += ctk
    SUBDIR += fep
    SUBDIR += git
    SUBDIR += glimpse
    SUBDIR += ical
    SUBDIR += ispell
    SUBDIR += kp
    SUBDIR += less
    SUBDIR += linuxls
    SUBDIR += mc
RESTRICTED += mmv               # restrictive copyright
    SUBDIR += mshell
    SUBDIR += recode
    SUBDIR += rman
    SUBDIR += screen
    SUBDIR += team
    SUBDIR += tkinfo
    SUBDIR += tkman

.include <bsd.port.subdir.mk>
