# $Id$
#

    SUBDIR += etlfonts
    SUBDIR += freefonts
    SUBDIR += getbdf
    SUBDIR += sharefonts
    SUBDIR += tkfont
    SUBDIR += ttmkfdir
    SUBDIR += xfed
    SUBDIR += xmbdfed

.include <bsd.port.subdir.mk>
