# New ports collection makefile for:    bpatch
# Version required:     no version information
# Date created:         18 March 1996
# Whom:                 joerg
#
# $Id$
#

DISTNAME=	bpatch
PKGNAME=	bpatch-1.0
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org

NO_WRKSUBDIR=   yes

.include <bsd.port.mk>
