# New ports collection makefile for:	unclutter
# Version required:	-8
# Date created:		03 Aug 1996
# Whom:			shanee@rabbit.augusta.de
#
# $Id$
#

DISTNAME=	unclutter
EXTRACT_SUFX=	-8.tar.gz
PKGNAME=	unclutter-8
MASTER_SITES=	ftp://ftp.cs.umn.edu/packages/X11/contrib/utilities/ \
		ftp://csg.uwaterloo.ca/pub/lhf/net/ \
		ftp://ftp.univ-angers.fr/pub2/X11/contrib/utilities/ \
		ftp://ftp.huji.ac.il/mirror/X11/contrib/utilities/ \
		ftp://ftp.rz.uni-wuerzburg.de/pub/X11/contrib/utilities/

CATEGORIES+=	misc

MAINTAINER=	shanee@rabbit.augusta.de

USE_IMAKE=	yes

.include <bsd.port.mk>
