# New ports collection makefile for:	jove
# Version required:	4.14.6
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	jove-4.14.10
MASTER_SITES=	ftp://relay.cs.toronto.edu/pub/moraes/jove/

.include <bsd.port.mk>
