# New ports collection makefile for:	jove
# Version required:	4.16
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	jove-4.16
CATEGORIES+=	editors
MASTER_SITES=	ftp://relay.cs.toronto.edu/pub/moraes/jove/
EXTRACT_SUFX=	.tar.gz

WRKSRC=		${WRKDIR}/jove

.include <bsd.port.mk>
