#!/bin/sh
#
# $FreeBSD$

oopath=%%PREFIX%%/OpenOffice.org%%RELEASE_NR%%/program/
program=`echo $0 | sed -e 's|.*-%%ELEASE_NR%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
