# New ports collection makefile for:    xmille
# Version required:     2.0
# Date created:         30 Dec 1994
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xmille
MASTER_SITES=	ftp://gatekeeper.dec.com/.b/X11-contrib/
USE_IMAKE=      yes
EXTRACT_SUFX=   .tar.Z
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
