# New ports collection makefile for:    mplex
# Version required:     1.1
# Date created:         Wed Jul 31 20:54:54 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $Id$
#

DISTNAME=	mplex-1.1

CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.informatik.tu-muenchen.de/pub/comp/graphics/mpeg/mplex/

MAINTAINER=	erich@FreeBSD.org

MAN1=		mplex.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
