# New ports collection makefile for:	popper
# Version required:	2.2
# Date created:		1 April 1995
# Whom:			pst
#
# $Id$
#

DISTNAME=	qpop2.2
PKGNAME=	qpop-2.2
CATEGORIES+=	mail
MASTER_SITES=	ftp://ftp.qualcomm.com/quest/unix/servers/popper/
EXTRACT_SUFX=	.tar.Z
NO_PACKAGE=	"Needs POP UID"

MAINTAINER=	pst@freebsd.org

WRKSRC=		${WRKDIR}/qpopper2.2

.include <bsd.port.mk>
