# New ports collection makefile for:	popper
# Version required:	2.1.3
# Date created:		06 October 1994
# Whom:			pst
#
# $Id$
#

DISTNAME=	qpop2.1.3-r5
MASTER_SITES=	ftp://ftp.qualcomm.com/quest/unix/servers/popper/
CATEGORIES+=	mail
EXTRACT_SUFX=	.tar.Z
WRKSRC=		${WRKDIR}/qpopper2.1.3

.include <bsd.port.mk>
