# New ports collection makefile for:    gshar+gunshar
# Version required:     4.1.3
# Date created:         28 Dec 1994
# Whom:                 ache
#
# $Id$
#
DISTNAME=       sharutils-4.1.3
MASTER_SITES=   ftp://ftp.iro.umontreal.ca/pub/contrib/pinard/
GNU_CONFIGURE=  YES
CONFIGURE_ARGS= --program-prefix=g --disable-uucode --prefix=${PREFIX}
INSTALL_TARGET= install install-man

.include <bsd.port.mk>
