# New ports collection makefile for:	beav
# Version required:	1.40-7 (debian)
# Date created:		01 July 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $Id$
#

DISTNAME=	beav_140-7
PKGNAME=	beav-1.40.7
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.debian.org/debian/bo/source/editors/

MAINTAINER=	tg@FreeBSD.org

WRKSRC=		${WRKDIR}/beav-140
PATCH_STRIP=	-p1

.include <bsd.port.mk>
