# New ports collection makefile for:    manck
# Version required:     1.0
# Date created:         10 September 1995
# Whom:                 joerg
#
# $Id$
#

DISTNAME=       manck-1.2
CATEGORIES+=	sysutils
MASTER_SITES=   ftp://freefall.freebsd.org/pub/FreeBSD/LOCAL_PORTS/

MAINTAINER=     wosch@FreeBSD.org

.include <bsd.port.mk>
