# New ports collection makefile for: pips for EPSON PM-770C
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES?=	japanese print linux
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		770

do-install:     # empty

.include "${MASTERDIR}/Makefile"
