# $Id$
#

    SUBDIR += ImageMagick
    BROKEN += Mesa              # doesn't install
    SUBDIR += aero
    SUBDIR += dore
    SUBDIR += hpscan
    SUBDIR += jpeg
    SUBDIR += mpeg-lib
    SUBDIR += mpeg_play
    SUBDIR += netpbm
    SUBDIR += pixmap
    SUBDIR += png
    SUBDIR += povray
    SUBDIR += spigot
    SUBDIR += tgif
    SUBDIR += tiff
    SUBDIR += vcg
    SUBDIR += xanim
    SUBDIR += xbmbrowser
    SUBDIR += xdl
    SUBDIR += xfig
    SUBDIR += xfractint
    SUBDIR += xgrasp
    SUBDIR += xli
    SUBDIR += xpaint
    SUBDIR += xpdf
    SUBDIR += xpm
    SUBDIR += xv

.include <bsd.port.subdir.mk>
