# $Id$
#
# BROKEN: Mesa (doesn't install)
# BROKEN: vcg (can't connect to ftp site)
#

SUBDIR=	ImageMagick dore jpeg mpeg-lib mpeg_play netpbm \
	pixmap povray tiff xanim xfig xli xpaint xpm xv

.include <bsd.port.subdir.mk>
