# New ports collection makefile for:	kinput2-canna
# Version required:	2.0p4
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	ja-kinput2-canna-2.0.4
CANNA=		yes

MASTERDIR=	${.CURDIR}/../kinput2-wnn4/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
