# New ports collection makefile for:    lv
# Version required:     4.40
# Date created:         Fri Nov  6 09:06:33 PST 1998
# Whom:                 sumikawa@kame.net
#
# $Id$
#

DISTNAME=	lv440
PKGNAME=	lv-4.40
CATEGORIES=	misc
MASTER_SITES=	http://www.ff.iij4u.or.jp/~nrt/freeware/

MAINTAINER=	sumikawa@kame.net

MAN1=		lv.1

.include <bsd.port.mk>
