# New ports collection makefile for:    xcdplayer
# Version required:     2.2
# Date created:         30 Sep 1994
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xcdplayer-2.2
CATEGORIES+=	audio
MASTER_SITES=	ftp://dutepp0.et.tudelft.nl/pub/Unix/Sun/

USE_IMAKE=      yes

.include <bsd.port.mk>
