# New ports collection makefile for:    xcdplayer
# Version required:     2.2
# Date created:         30 Sep 1994
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xcdplayer-2.2
MASTER_SITES=   ftp://sunsite.unc.edu/pub/X11/contrib/
USE_IMAKE=      yes
MAN1=		xcdplayer.1

.include <bsd.port.mk>
