# New ports collection makefile for:	qpage
# Version required:	3.2
# Date created:		02 Aug 1997
# Whom:			joes@seaport.net
#
# $Id$
#

DISTNAME=	qpage-3.2
CATEGORIES=	comms
MASTER_SITES=	http://www.qpage.org/download/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	joes@seaport.net

MAN1=		qpage.1

.include <bsd.port.mk>
