# New ports collection makefile for:	tvision
# Version required:			0.3
# Date created:				16 February 1997
# Whom:					Sandro Sigala
#
# $Id$
#

DISTNAME=	tvision-0.4
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ssigala@globalnet.it

HAS_CONFIGURE=	yes

.include <bsd.port.mk>
