# New ports collection makefile for:	xdaliclock
# Version required:			2.11
# Date created:				10th February 1995
# Whom:					gpalmer
#
# $Id$
#

DISTNAME=	xdaliclock-2.11
CATEGORIES=	x11-clock
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	gpalmer@FreeBSD.ORG

USE_IMAKE=	yes
MAN1=		xdaliclock.1

.include <bsd.port.mk>
