# New ports collection makefile for:	xdaliclock
# Version required:			2.08
# Date created:				10th February 1995
# Whom:					gpalmer
#
# $Id$
#

DISTNAME=	xdaliclock-2.08
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	gpalmer@FreeBSD.ORG

USE_IMAKE=	yes

.include <bsd.port.mk>
