# New ports collection makefile for:	xdaliclock
# Version required:			2.11
# Date created:				10th February 1995
# Whom:					gpalmer
#
# $Id$
#

DISTNAME=	xdaliclock-2.13
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.jwz.org/xdaliclock/ \
		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	gpalmer@FreeBSD.ORG

USE_IMAKE=	yes
MAN1=		xdaliclock.1

.include <bsd.port.mk>
