# Makefile for:		rplay - Network audio player   
# Version required:	3.2.0b2
# Date created:		16 March 1995  
# Whom:			rmallory@csusb.edu
#
# $Id$
#

DISTNAME=	rplay-3.2.0b2
MASTER_SITES=	ftp://ftp.sdsu.edu/pub/rplay/
HAS_CONFIGURE=	yes
USE_GMAKE=	yes
.include <bsd.port.mk>
