#!/bin/sh

#
# Copyright (c)2000-2001 by MarcusCom, Inc.  All rights reserved.
# $Id$
#

# Change this to your path to jre
JRE=%%LOCALBASE%%/bin/javavm
# End changeable things

CLASSPATH=%%PREFIX%%/share/java/confregdecode.jar:${CLASSPATH}

exec ${JRE} -classpath ${CLASSPATH} com.marcuscom.confregdecode.ConfregDecode
