# New ports collection makefile for:	jvim3 for Canna and Wnn4
# Version required:	3.0-j1.3i
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	ja-jvim-canna+wnn4-3.0.1.3i

CANNA=		yes
WNN4=		yes

.include "${.CURDIR}/../jvim3/Makefile"
