# $Id$
#

    SUBDIR += imm
    SUBDIR += mbone_vcr
    SUBDIR += nte
    SUBDIR += rtpmon
    SUBDIR += rtptools
    SUBDIR += sdr
    SUBDIR += sdr25
    SUBDIR += speak_freely
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb

.include <bsd.port.subdir.mk>
