# $Id$
#

    BROKEN += imm
    SUBDIR += mbone_vcr
    SUBDIR += nte
    BROKEN += nv
    SUBDIR += rtpmon
    SUBDIR += sdr
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb

.include <bsd.port.subdir.mk>
