# $Id$
#

    SUBDIR += imm
    SUBDIR += mbone_vcr
    SUBDIR += nte
    SUBDIR += nv
    SUBDIR += rtpmon
    SUBDIR += sdr
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb

.include <bsd.port.subdir.mk>
