# New ports collection makefile for: zh Big5/GB-ized Netcape
# Date created:		23 Oct 2000
# Whom:			Jing-Tang Keith Jang <keith@FreeBSD.org>
#
# $FreeBSD$
#

BROWSER_NAME=	navigator

MASTERDIR=	${.CURDIR}/../netscape47-communicator
.include	"${.CURDIR}/../netscape47-communicator/Makefile"
