# New ports collection makefile for:	netpbm
# Version required:	1mar1994
# Date created:		?
# Whom:			jmz (original)
#
# $Id$
#

DISTNAME=	netpbm
DISTFILES=	netpbm-1mar1994.tar.gz
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
MAINTAINER=	asami@FreeBSD.ORG
USE_IMAKE=	yes

LIB_DEPENDS=	tiff\\.3\\.:${PORTSDIR}/graphics/tiff

.include <bsd.port.mk>
