# New ports collection makefile for:	xdu
# Version required:	R6 contrib tape
# Date created:		9 February 1995
# Whom:			asami
#
# $Id$
#

DISTNAME=	xdu-3.0
EXTRACT_SUFX=	.tar.Z
USE_IMAKE=	yes
MASTER_SITES=	ftp://ftp.arl.mil/pub/
MAINTAINER=	asami@FreeBSD.ORG
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
