# New ports collection makefile for:	xdu
# Version required:	R6 contrib tape
# Date created:		9 February 1995
# Whom:			asami
#
# $Id$
#

DISTNAME=	xdu-3.0
CATEGORIES=	sysutils x11
MASTER_SITES=	ftp://ftp.arl.mil/pub/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	asami@FreeBSD.ORG

NO_WRKSUBDIR=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
