# $Id$
#
SUBDIR= acm golddig jetpack oneko nethack xasteroids xboard xboing xchomp \
	xemeraldia xinvaders \
	xjewel xlife xmille xmine xminesweep xmj xmris xpipeman xrobots xsol \
	xtetris

.include <bsd.port.subdir.mk>
