# $Id$
#

   SUBDIR += acm
   SUBDIR += golddig
   SUBDIR += jetpack
   SUBDIR += nethack
   SUBDIR += oneko
   SUBDIR += tksol
   SUBDIR += xasteroids
   SUBDIR += xboard
   SUBDIR += xboing
   SUBDIR += xchomp
   SUBDIR += xemeraldia
   SUBDIR += xevil
   SUBDIR += xinvaders
   SUBDIR += xjewel
   SUBDIR += xlife
   SUBDIR += xmille
   SUBDIR += xmine
   SUBDIR += xminesweep
   SUBDIR += xmj
   SUBDIR += xmris
   SUBDIR += xonix
   SUBDIR += xpipeman
   SUBDIR += xrisk
   SUBDIR += xrobots
   SUBDIR += xsol
   SUBDIR += xtetris
   SUBDIR += xtic

.include <bsd.port.subdir.mk>
