# $Id$
#
# BROKEN: xpipeman (can't ftp)
# BROKEN: xrobots (can't ftp)
#

SUBDIR= acm golddig jetpack nethack oneko xasteroids xboard xboing \
	xchomp xemeraldia xevil xinvaders \
	xjewel xlife xmille xmine xminesweep xmj xmris xonix xrisk xsol \
	xtetris

.include <bsd.port.subdir.mk>
