# New ports collection makefile for:    xblackjack
# Version required:     2.2
# Date created:         
# Whom:                 erich@FreeBSD.org
#
# $Id$
#

DISTNAME=	xblackjack-2.2
CATEGORIES+=	games
MASTER_SITES=	ftp://ftp.x.org/contrib/games/

MAINTAINER=	erich@FreeBSD.org

REQUIRES_MOTIF=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
