# New ports collection makefile for:	ghostview
# Version required:	1.5
# Date created:		21 October 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	ghostview-1.5
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_GNU}

MAINTAINER=	ports@FreeBSD.org

RUN_DEPENDS=	gs:${PORTSDIR}/print/ghostscript

USE_IMAKE=	yes

.include <bsd.port.mk>
