# New ports collection makefile for:	ghostview
# Version required:	1.5
# Date created:		21 October 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	ghostview-1.5
USE_IMAKE=	yes
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu/
CATEGORIES+=	printing
EXEC_DEPENDS=	gs:${PORTSDIR}/print/ghostscript

.include <bsd.port.mk>
