# New ports collection makefile for:    icon
# Version required:     9.3
# Date created:         05 April 1995
# Whom:                 thomas@ghpc8.ihf.rwth-aachen.de
#
# $Id$
#

DISTNAME=       unix
EXTRACT_SUFX=	.tgz
PKGNAME=	icon-9.3
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.cs.arizona.edu/icon/packages/unix/

MAINTAINER=	ports@freebsd.org

DIST_SUBDIR=	icon
NO_WRKSUBDIR=	true
ALL_TARGET=	Icon Icon-iconc

.include <bsd.port.mk>
