# New ports collection makefile for:	xmbdfed
# Version required:	3.4
# Date created:		June 20, 1997
# Whom:			jfieber
#
# $Id$
#

DISTNAME=	xmbdfed-3.7
CATEGORIES=	x11-fonts
MASTER_SITES=	ftp://crl.nmsu.edu/CLR/multiling/General/

PATCH_SITES=	${MASTER_SITES}
PATCHFILES=	xmbdfed-3.7.patch1

MAINTAINER=	jfieber@FreeBSD.ORG

USE_X_PREFIX=	yes
REQUIRES_MOTIF=	yes

MAN1=		xmbdfed.1

.include <bsd.port.mk>
