# $Id$
#

    SUBDIR += abacus
    SUBDIR += cal
    SUBDIR += cbb
    SUBDIR += gnomepim
    SUBDIR += gnucash
    SUBDIR += ical
    SUBDIR += korganizer
    SUBDIR += kproject
    SUBDIR += offix-trash
    SUBDIR += plan
    SUBDIR += sliderule
    SUBDIR += teapot
    SUBDIR += xcalendar
    SUBDIR += xinvest
    SUBDIR += xmaddressbook
    SUBDIR += xmdiary
    SUBDIR += xopps
    SUBDIR += xpostit
    SUBDIR += xpostitPlus
    SUBDIR += xrolo
    SUBDIR += zorro

.include <bsd.port.subdir.mk>
