# New ports collection makefile for:  movemail
# Version required:    1.0
# Date created:        1997/09/09
# Whom:                wosch
#
# $Id$
#

DISTNAME=      movemail-1.0
CATEGORIES=    mail
MASTER_SITES=  http://www.freebsd.org/~wosch/src/

MAINTAINER=    wosch@FreeBSD.ORG

.include <bsd.port.mk>
