# New ports collection makefile for:	tkinfo
# Version required:     0.8
# Date created:         16 Jan 1995
# Whom:                 thomas@ghpc8.ihf.rwth-aachen.de
#
# $Id$
#

DISTNAME=	tkinfo-0.8
CATEGORIES=	misc
MASTER_SITES=	http://emile.math.ucsb.edu:8000/

MAINTAINER=	tg@freebsd.org

RUN_DEPENDS=	wish4.1:${PORTSDIR}/x11/tk41

.include <bsd.port.mk>
