# New ports collection makefile for:    Mesa
# Version required:     2.1
# Date created:         3 Feb 1997
# Whom:                 paulo@isr.uc.pt
#
# $Id$
#

DISTNAME=       Mesa-2.1
CATEGORIES=	graphics
MASTER_SITES= 	ftp://iris.ssec.wisc.edu/pub/Mesa/

MAINTAINER=	ports@freebsd.org

ALL_TARGET=	freebsd
USE_X11=	yes

.include <bsd.port.mk>
