# New ports collection makefile for:    xscreensaver
# Version required:     1.25
# Date created:         10 July 1995
# Whom:                 asami
#
# $Id$
#

DISTNAME=	xscreensaver-1.25
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	asami@FreeBSD.ORG

LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

.include <bsd.port.mk>
