# $Id$
#

    SUBDIR += aish
    SUBDIR += btoa
    SUBDIR += ish
    SUBDIR += kdesupport
    SUBDIR += kdesupport11
    SUBDIR += mimepp
    SUBDIR += mpack
    SUBDIR += p5-Convert-UU
    SUBDIR += p5-MIME-Base64
    SUBDIR += recode
    SUBDIR += trans
    SUBDIR += uudeview
    SUBDIR += uudx
    SUBDIR += uulib
    SUBDIR += xdeview

.include <bsd.port.subdir.mk>
