# $Id$
#

    SUBDIR += btoa
    SUBDIR += mpack
    SUBDIR += p5-Convert-UU
    SUBDIR += recode
    SUBDIR += trans
    SUBDIR += uudeview
    SUBDIR += uudx
    SUBDIR += uulib
    SUBDIR += xdeview

.include <bsd.port.subdir.mk>
