# $Id$
#

    SUBDIR += aish
    SUBDIR += btoa
    SUBDIR += i18ntools
    SUBDIR += ish
    SUBDIR += kdesupport
    SUBDIR += kdesupport-i18n-11
    SUBDIR += kdesupport11
    SUBDIR += libutf-8
    SUBDIR += mimepp
    SUBDIR += mpack
    SUBDIR += p5-Convert-UU
    SUBDIR += p5-MIME-Base64
    SUBDIR += recode
    SUBDIR += trans
    SUBDIR += unix2dos
    SUBDIR += uudeview
    SUBDIR += uudx
    SUBDIR += uulib
    SUBDIR += xdeview

.include <bsd.port.subdir.mk>
