# New ports collection makefile for:    SWIG
# Version required:     1.0b1
# Date created:         19 April 1996
# Whom:                 jkh
#
# $Id$
#

DISTNAME=	swig1.0b1
PKGNAME=	swig-1.0b1
CATEGORIES+=	devel
MASTER_SITES=	ftp://ftp.cs.utah.edu/pub/beazley/SWIG/

MAINTAINER=	jkh@FreeBSD.org

WRKSRC=		${WRKDIR}/SWIG1.0b1

.include <bsd.port.mk>
