# $Id$
#

    SUBDIR += a2ps
    SUBDIR += afm
    SUBDIR += apsfilter
    SUBDIR += dvi2xx
    SUBDIR += dvips
    SUBDIR += dviselect
    SUBDIR += ghostscript
    SUBDIR += ghostscript3
    SUBDIR += ghostview
    SUBDIR += latex
    SUBDIR += latex209
    SUBDIR += makeindex
    SUBDIR += mltex
    SUBDIR += musixtex
    SUBDIR += psutils
    SUBDIR += rtf2latex
    SUBDIR += teTeX
    SUBDIR += tex
    SUBDIR += texinfo
    SUBDIR += tr2latex
    SUBDIR += transfig
    SUBDIR += xdvi
    SUBDIR += xtexshell

.include <bsd.port.subdir.mk>
