# $Id$
#
SUBDIR=	a2ps afm dvi2xx dvips dviselect ghostscript ghostview \
	latex latex209 makeindex mltex psutils \
	rtf2latex \
	tex texinfo tr2latex transfig xdvi \
	xtexshell

.include <bsd.port.subdir.mk>
