# $Id$
#
SUBDIR=	a2ps afm dvi2xx dvips dviselect ghostscript ghostview psutils \
	rtf2latex \
	tex latex209 latex makeindex mltex texinfo tr2latex transfig xdvi \
	xtexshell

.include <bsd.port.subdir.mk>
