# New ports collection makefile for: English PK fonts at 400dpi
# Version required:	?
# Date created:		06 Nov 1998
# Whom:			Satoshi Asami <asami@freebsd.org>
#
# $Id$
#

RESOLUTION=	400
MASTERDIR=	${.CURDIR}/../pkfonts300

BROKEN= 'fetch'

.include	"${MASTERDIR}/Makefile"
