# New ports collection makefile for:	xbuffy
# Version required:	3.2.1
# Date created:		18 June 1995
# Whom:			dchapes@zeus.leitch.com
#
# $Id$
#

DISTNAME=	xbuffy3.2.1
PKGNAME=	xbuffy-3.2.1
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	dchapes@zeus.leitch.com

USE_IMAKE=	yes

.include <bsd.port.mk>
