# New ports collection makefile for:    tintin++
# Version required:     1.5pl6
# Date created:         15 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       tintin++v1.5pl6
EXTRACT_SUFX=   .tar.Z
MASTER_SITES=   ftp://princeton.edu/pub/tintin++/dist/
CATEGORIES+=	networking
WRKSRC=         ${WRKDIR}/tintin++/src
GNU_CONFIGURE=	YES

.include <bsd.port.mk>
