# New ports collection makefile for:    tracker
# Version required:     4.36
# Date created:         2 Oct 1994
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       tracker
PKGNAME=        tracker-4.36
CATEGORIES+=	audio
MASTER_SITES=   ftp://ftp.ens.fr/pub/dmi/users/espie/beta/
DISTFILES=      tracker-4.36.tar.Z

MAINTAINER=     ache@FreeBSD.ORG

USE_GMAKE=      yes
MAKE_FLAGS=     MACHINE=freebsd CC=cc INSTALL=install -f
INSTALL_TARGET= install install.info

.include <bsd.port.mk>
