# New ports collection makefile for:    tracker
# Version required:     4.3
# Date created:         2 Oct 1994
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       tracker
DISTFILES=	tracker-4.3-linux.tar.gz
MASTER_SITES=   ftp://sunsite.unc.edu/pub/Linux/apps/sound/players/

.include <bsd.port.mk>
