# New ports collection makefile for:	Eric Young's SSL/Crypto Library
# Version required:	0.6.3
# Date created:		1 July 1996
# Whom:			markm
#
# $Id$
#

DISTNAME=		SSLeay-0.6.3
CATEGORIES+=		devel security
MASTER_SITES=		ftp://psych.psy.uq.oz.au/pub/Crypto/SSL/

MAINTAINER=		markm@FreeBSD.ORG

HAS_CONFIGURE=		yes
CONFIGURE_SCRIPT=	util/FreeBSD.sh
MAKEFILE=		Makefile.FreeBSD

RESTRICTED=		"Cryptography"

.include <bsd.port.mk>
