# New ports collection makefile for:	motif
# Version required:	1.2
# Date created:		5 December 1994
# Whom:			asami
#
# $Id$
#

DISTNAME=	Motif-1.2
CATEGORIES=	x11-toolkits
DISTFILES=	# empty

USE_X_PREFIX=	yes
NO_BUILD=	yes
NO_INSTALL=	yes
IS_INTERACTIVE=	yes

.include <bsd.port.mk>
