# New ports collection makefile for:	kcfonts
# Version required:			1.01
# Date Created:				5 Dec 1997
# Whom:					Ming-I Hseh <PA@FreeBSD.Ntu.edu.TW>
#
# $Id$
#

DISTNAME=	kcfonts-1.01
PKGNAME=	zh-kcfonts-1.01
CATEGORIES=	chinese x11
MASTER_SITES=	ftp://freebsd.ntu.edu.tw/freebsd/taiwan/ \
		ftp://freebsd.ee.ntu.edu.tw/freebsd/taiwan/ \
		ftp://ftp.edu.tw/OS/FreeBSD/00MIRROR/freebsd.ntu.edu.tw/taiwan/

MAINTAINER=	PA@FreeBSD.ee.Ntu.edu.TW

USE_X11=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
