# New ports collection makefile for:	xosview
# Version required:	1.6.2.a
# Date created:		19 Nov 1997
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $Id$
#

DISTNAME=	xosview-1.6.2.a
CATEGORIES=	sysutils
MASTER_SITES=	http://lore.ece.utexas.edu/~bgrayson/xosview/ \
		http://lambic.physics.montana.edu/xosview/

MAINTAINER=	handy@physics.montana.edu

FETCH_BEFORE_ARGS=	-b
USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
MAN1=		xosview.1

# BROKEN=	DiskMeter broken for 3.0+

.include <bsd.port.mk>
