# $Id$
#
SUBDIR=	Xaw3d color_xterm emu fvwm iv ivs jpeg kterm olvwm pcb piewm tk \
	tkhfs xanim xarchie \
	xcdplayer xdvi xearth xli xlockmore xpm xsnow xtexshell xv \
	ImageMagick ctwm mpeg-lib tiff

#
# imm & nv depends on tk, so might as well build tk first...
#
SUBDIR+= imm nv

.include <bsd.port.subdir.mk>
