# $Id$
#
SUBDIR= Xaw3d color_xterm ctwm emu fvwm g3view olvwm piewm \
	rxvt sxpc tk tkhfs tkman tvtwm  xdaliclock xearth xfed xfm \
	xkeycaps xlockmore xphoon xsnow xview-config xview-lib xview-clients

#
# These depend on tk, so might as well build tk first...
#
SUBDIR+= blt

.include <bsd.port.subdir.mk>
