# $Id$
#

SUBDIR= XFree86 Xaw3d blt color_xterm ctwm emiclock emu fvwm g3view \
	iv olvwm piewm \
	rxvt sxpc tk tkhfs tkinfo tkman tvtwm \
	x3270 xcolors xdaliclock xdtm xearth xfed xfm xgrab \
	xkeycaps xloadimage xlockmore xperfmon xphoon xsnow \
	xview-config xview-lib xview-clients

.include <bsd.port.subdir.mk>
