# New ports collection makefile for:	x3270
# Version required:	3.0.3.7
# Date created:		31 January 1995
# Whom:			janek
#
# $Id$
#

DISTNAME=	x3270-3.0.3.7
CATEGORIES=	x11 emulators
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications/x3270

USE_IMAKE=	yes

WRKSRC=		${WRKDIR}/x3270-3.0.3

.include <bsd.port.mk>
