# New ports collection makefile for:    ncftp 2 BETA
# Version required:     2.0.0 BETA 6
# Date created:         4 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       ncftp-2.0b6
EXTRACT_SUFX=   .tgz
MASTER_SITES=   ftp://ftp.cs.unl.edu/pub/ncftp/BETA/
GNU_CONFIGURE=  YES

.include <bsd.port.mk>
