# New ports collection makefile for:	mule with sj3
# Version required:	2.3
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	ja-mule-sj3-2.3
CATEGORIES=	japanese editors

SJ3=		yes

.include "${.CURDIR}/../../editors/mule/Makefile"
