# New ports collection makefile for:	pstack
# Date created:		1 May 2002
# Whom:			Peter Edwards <pmedwards@eircom.net>
#
# $FreeBSD$
# $Id$
#

PORTNAME=	pstack
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://bsd-pstack.sourceforge.net/releases/

MAINTAINER=	pmedwards@eircom.net

ONLY_FOR_ARCHS=	i386

MANCOMPRESSED=	yes
MAN1=	pstack.1

.include <bsd.port.mk>
