# $Id$
#

    SUBDIR += cnews
    SUBDIR += inn
    SUBDIR += knews
    SUBDIR += nn
    SUBDIR += nn-current
    SUBDIR += nntp
    SUBDIR += nntpbtr
    SUBDIR += rkive
    SUBDIR += slnr
    SUBDIR += slurp
    SUBDIR += suck
    SUBDIR += tin
    SUBDIR += trn
    SUBDIR += xvnews

.include <bsd.port.subdir.mk>
