# New ports collection makefile for:	tvtwm
# Version required:	pl11
# Date created:		5th December 1994
# Whom:			gpalmer
#
# $Id$
#

DISTNAME=	tvtwm
DISTFILES=	tvtwm.pl11.tar.gz
USE_IMAKE=	yes
MASTER_SITES=	ftp://ftp.x.org/contrib/window_managers/
MAINTAINER=	gpalmer@FreeBSD.ORG
LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

.include <bsd.port.mk>
