# New ports collection makefile for:	xskat
# Version required:	3.0
# Date created:		27 Apr 1996
# Whom:			Thomas Gellekum <tg@FreeBSD.ORG>
#
# $Id$
#

DISTNAME=	xskat-3.0
CATEGORIES=	games
MASTER_SITES=	http://www.gulu.net/xskat/

MAINTAINER=	tg@FreeBSD.ORG

WRKSRC=		${WRKDIR}/xskat
USE_IMAKE=	yes
MAN1=		xskat.1

.include <bsd.port.mk>
