# New ports collection makefile for:	screen
# Version required:     3.6.1
# Date created:         25 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       screen-3.6.1
NCFTPFLAGS=     -PN
MASTER_SITES=   ftp://ftp.uni-erlangen.de/pub/utilities/screen/
GNU_CONFIGURE=	YES

.include <bsd.port.mk>
