# New ports collection makefile for:	xneko
# Version required:	4.4BSD-Lite
# Date created:		22 December 1995
# Whom:			markm
#
# $Id$
#

DISTNAME=	xneko
PKGNAME=	xneko-4.4
CATEGORIES=	x11 games
MASTER_SITES=	ftp://ftp.cdrom.com/pub/bsd-sources/4.4BSD-Lite/usr/src/games/

MAINTAINER=	markm@FreeBSD.ORG

USE_X11=	yes

.include <bsd.port.mk>
