# New ports collection makefile for:    figlet
# Version required:     2.2
# Date created:         Sat July 20, 1996
# Whom:                 David O'Brien (obrien@cs.ucdavis.edu)
#
# $Id$
#

DISTNAME=	figlet22
PKGNAME=	figlet-2.2
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.nicoh.com/pub/figlet/program/unix/  \
		ftp://ftp.wwa.com/pub/Scarecrow/Figlet/Unix/

MAINTAINER=     obrien@cs.ucdavis.edu

MAN6=		figlet.6

.include <bsd.port.mk>
