# $Id$
#

    SUBDIR += Wnn
    SUBDIR += afterstep
    SUBDIR += h2ps
    SUBDIR += hanterm
    SUBDIR += hanterm-autofont
    SUBDIR += hanterm-xf86
    SUBDIR += hanyangfonts
    SUBDIR += johabfonts
    SUBDIR += nvi-euc-kr
    SUBDIR += nvi-iso-2022-kr
    SUBDIR += pinetreefonts

.include <bsd.port.subdir.mk>
