# $Id$
#

    SUBDIR += Wnn
    SUBDIR += afterstep
    SUBDIR += elm
    SUBDIR += h2ps
    SUBDIR += hanterm
    SUBDIR += hanterm-autofont
    SUBDIR += hanterm-xf86
    SUBDIR += hanyangfonts
    SUBDIR += hcode
    SUBDIR += helvis
    SUBDIR += johabfonts
    SUBDIR += nhpf
    SUBDIR += nvi-euc-kr
    SUBDIR += nvi-iso-2022-kr
    SUBDIR += pine
    SUBDIR += pinetreefonts

.include <bsd.port.subdir.mk>
