# New ports collection makefile for:	bash
# Version required:     2.0
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       bash-2.0
CATEGORIES=	shells
MASTER_SITES=   ftp://slc2.ins.cwru.edu/pub/dist/

MAINTAINER=     ache@FreeBSD.ORG

GNU_CONFIGURE=  Yes

MAN1=           bash.1 bashbug.1

.include <bsd.port.mk>
