# New ports collection makefile for:	bash
# Version required:     1.14.7
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       bash-1.14.7
CATEGORIES=	shells
MASTER_SITES=   ftp://slc2.ins.cwru.edu/pub/dist/

MAINTAINER=     ache@FreeBSD.ORG

WRKSRC=         ${WRKDIR}/${DISTNAME}
# Don't compress manpages or .so not works.

.include <bsd.port.mk>
