# New ports collection makefile for:	bash
# Version required:	1.14.2
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

GNU_MAKE=	yes
DISTNAME=	bash-1.14.2
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu/

.include <bsd.port.mk>
