# New ports collection makefile for:	leafnode
# Version required:	1.4
# Date created:		10 April 1996
# Whom:			Brian Somers <brian@awfulhak.org>
#
# $Id$
#

DISTNAME=	leafnode-1.4
CATEGORIES=	news
MASTER_SITES=	ftp://ftp.troll.no/freebies/leafnode/

MAINTAINER=	brian@awfulhak.org

MAN8=		leafnode.8 fetch-news.8 texpire.8 checkgroups.8

.include <bsd.port.mk>
