# $Id$
#

    SUBDIR += axe
    SUBDIR += e93
    SUBDIR += emacs
    SUBDIR += jove
    SUBDIR += mule
    SUBDIR += tkHTML
    SUBDIR += uemacs
    SUBDIR += uzap
    SUBDIR += vile
    SUBDIR += xcoral
    SUBDIR += xemacs
    SUBDIR += xvile

    NOBUILD += ashe		# requires motif

.include <bsd.port.subdir.mk>
