# $Id$
#

    SUBDIR += axe
    SUBDIR += asedit
    SUBDIR += beav
    SUBDIR += bpatch
    SUBDIR += e93
    SUBDIR += emacs
    SUBDIR += jove
    SUBDIR += mule
    SUBDIR += nedit
    SUBDIR += uemacs
    SUBDIR += uzap
    SUBDIR += vile
    SUBDIR += vim
    SUBDIR += xcoral
    SUBDIR += xed
    SUBDIR += xemacs
    SUBDIR += xvile

.include <bsd.port.subdir.mk>
