# $Id$
#

    SUBDIR += babel
    SUBDIR += hmmer
    SUBDIR += kinemage
    SUBDIR += mopac
    SUBDIR += povchem
    SUBDIR += psi88
    SUBDIR += rasmol
    SUBDIR += seaview
    SUBDIR += tinker

.include <bsd.port.subdir.mk>
