# New ports collection makefile for:    arc
# Version required:     5.21e
# Date created:         31 Dec 1994
# Whom:                 ache
#
# $Id$
#
DISTNAME=       arc521e.pl8
EXTRACT_SUFX=   .tar.Z
MASTER_SITES=   ftp://ftp.kiae.su/unix/arcers/
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
