# New ports collection makefile for:    arc
# Version required:     5.21e
# Date created:         31 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       arc521e.pl8
PKGNAME=        arc-5.21e
CATEGORIES=	archivers
MASTER_SITES=   ftp://ftp.kiae.su/unix/arcers/
EXTRACT_SUFX=   .tar.Z

MAINTAINER=     ache@FreeBSD.ORG

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
