# New ports collection makefile for:    mswordview
# Version required:     0.5.2
# Date created:         Fri Nov  6 09:06:33 PST 1998
# Whom:                 sumikawa@kame.net
#
# $Id$
#

DISTNAME=	mswordview-0.5.2
CATEGORIES=	textproc
MASTER_SITES=	http://www.csn.ul.ie/~caolan/publink/mswordview/

MAINTAINER=	sumikawa@kame.net

GNU_CONFIGURE=	yes
WRKSRC=		$(WRKDIR)/mswordview

.include <bsd.port.mk>
