# New ports collection makefile for:    xmj
# Version required:	?
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xmj
CATEGORIES+=	games
MASTER_SITES=	ftp://ftp.cs.orst.edu/pub/src/X11R4/contrib/demos/

USE_IMAKE=	yes
NO_INSTALL_MANPAGES= yes

.include <bsd.port.mk>
