# New ports collection makefile for:    xmj
# Version required:	?
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xmj
PKGNAME=	xmj-1.0
CATEGORIES+=	games
MASTER_SITES=	ftp://forte.mathematik.uni-bremen.de/pub/unix/X11/

USE_IMAKE=	yes
NO_INSTALL_MANPAGES= yes

.include <bsd.port.mk>
