# New ports collection makefile for:    apache
# Version required:     1
# Date created:         Fri Aug 25 16:42:36 CDT 1995
# Whom:                 erich@rrnet.com
#
# $Id$
#

DISTNAME=	apache_1.0.0
PKGNAME=	apache-1.0.0
CATEGORIES+=	www
MASTER_SITES=	ftp://ftp.ast.cam.ac.uk/pub/WWW/apache/

MAINTAINER=	pst@freebsd.org

.include <bsd.port.mk>
