# New ports collection makefile for:    xkeycaps
# Version required:     2.31
# Date created:         12 February 1995
# Whom:                 jmz
#
# $Id$
#

DISTNAME=	xkeycaps-2.42
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
