# New ports collection makefile for:    xkeycaps
# Version required:     2.31
# Date created:         12 February 1995
# Whom:                 jmz
#
# $Id$
#

DISTNAME=	xkeycaps-2.31
CATEGORIES+=	x11
MASTER_SITES=	ftp://ftp.ibp.fr/pub/X11/contrib/applications/

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
