# $FreeBSD$

PREFIX?=	${DESTDIR}/usr/local
LIBDIR=		${PREFIX:S,^${DESTDIR},,}/lib

CFLAGS+=-D_PTHREADS -I../
CFLAGS+=-I../sysdeps/i386 -I../sysdeps/pthread -I../sysdeps/unix/sysv/linux
CXXFLAGS=	${CXXINCLUDES} ${CFLAGS}

installincludes:

.include "Makefile.inc"

#
# Override various things that are set in the main Makefile.
#

.undef SUBDIR
