# $FreeBSD$

DESTDIR=/usr/local/
LIBDIR= lib/

CFLAGS+=-D_PTHREADS -I../
CFLAGS+=-I../sysdeps/i386 -I../sysdeps/pthread -I../sysdeps/unix/sysv/linux

.include "/usr/src/gnu/lib/libgcc/Makefile"

#
# Override various things that are set in the main Makefile.
#

GCCDIR:=$(GCCDIR:T:S/^/\/usr\/src\/contrib\/&/)

LIB=	lgcc_r

.PATH: ${GCCDIR}/cp ${GCCDIR}
