# New ports collection makefile for: socket
# Version required:     1.1
# Date created:         14 August 1996
# Whom:                 wosch
#
# $Id$
#

DISTNAME=       socket-1.1
CATEGORIES=	sysutils net
MASTER_SITES=   ${MASTER_SITE_LOCAL}

MAINTAINER=     wosch@FreeBSD.org

MAN1=		socket.1

.include <bsd.port.mk>
