# New ports collection makefile for:	tcsh
# Version required:	6.05
# Date created:		22 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	tcsh-6.05
HOME_LOCATION=	ugle.unit.no:~ftp/pub/unix/tcsh

.include <bsd.port.mk>
