# New ports collection makefile for:	tcsh
# Version required:	6.05
# Date created:		22 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	tcsh-6.05
HOME_LOCATION=  ftp://tesla.ee.cornell.edu/pub/tcsh/tcsh-6.05.tar.gz

.include <bsd.port.mk>
