# New ports collection makefile for:    xcept
# Version required:     2.1.2
# Date created:         Sep 1, 1996
# Whom:                 joerg
#
# $Id$
#

DISTNAME=       xcept-2.1.2
CATEGORIES+=	comms
MASTER_SITES=   ftp://freefall.cdrom.com/pub/FreeBSD/LOCAL_PORTS/

MAINTAINER=     joerg@FreeBSD.ORG

WRKSRC=		${WRKDIR}/XCept-2.1.2

.include <bsd.port.mk>
