# $Id$
#

    SUBDIR += blas
    SUBDIR += calc
    SUBDIR += calctool
    SUBDIR += eispack
    SUBDIR += fftpack
    SUBDIR += freefem
    SUBDIR += fudgit
    SUBDIR += gnuplot
    SUBDIR += hexcalc
    SUBDIR += lapack
    SUBDIR += linpack
    SUBDIR += maxima
    SUBDIR += octave
    SUBDIR += oleo
    SUBDIR += ss
    SUBDIR += wingz
    SUBDIR += xgraph
    SUBDIR += xlispstat
    SUBDIR += xplot
    SUBDIR += xspread
    SUBDIR += xvgr

.include <bsd.port.subdir.mk>
