# $Id$
#

    SUBDIR += blas
    SUBDIR += calc
    SUBDIR += eispack
    SUBDIR += fudgit
    SUBDIR += gmp
    SUBDIR += gnuplot
    SUBDIR += hexcalc
    SUBDIR += linpack
RESTRICTED += maxima (license required)
    SUBDIR += octave
    SUBDIR += oleo
    SUBDIR += xgraph
    SUBDIR += xlispstat
    SUBDIR += xspread

.include <bsd.port.subdir.mk>
