# New ports collection makefile for:	logo
# Version required:	7.3
# Date created:		22 October 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	ucblogo
EXTRACT_SUFX=	.tar.Z
MASTER_SITES=	ftp://anarres.cs.berkeley.edu/pub/ucblogo/
MAKEFILE=	makefile
WRKSRC=	${WRKDIR}
HAS_CONFIGURE=	yes

.include <bsd.port.mk>
