# New ports collection makefile for:    fspclient
# Version required:     0.0-h+
# Date created:         7 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       fspclient.0.0-h+
EXTRACT_SUFX=   .tar.z
MASTER_SITES=   ftp://ftp.robots.ox.ac.uk/pub/ox.src/fspclient/
WRKSRC=		${WRKDIR}/fspclient
GNU_CONFIGURE=	YES

.include <bsd.port.mk>
