# New ports collection makefile for:    fspclient
# Version required:     0.0-h+
# Date created:         7 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       fspclient.0.0-h+
PKGNAME=        fspclient.0.0.h
CATEGORIES+=	networking
MASTER_SITES=   ftp://ftp.robots.ox.ac.uk/pub/ox.src/fspclient/
EXTRACT_SUFX=   .tar.z

MAINTAINER=     ache@FreeBSD.ORG

WRKSRC=		${WRKDIR}/fspclient
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
