# $Id$
#

    SUBDIR += asfiles
    SUBDIR += dfm
    SUBDIR += explorer
    SUBDIR += ezfm
    SUBDIR += filerunner
    SUBDIR += jafm
    SUBDIR += offix-files
    SUBDIR += q3dmenu
    SUBDIR += tkdesk
    SUBDIR += workplace
    SUBDIR += x-files
    SUBDIR += xfm

.include <bsd.port.subdir.mk>
