# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.5
# Date created:		29 Dec 1998
# Whom:			sada@FreeBSD.ORG
#
# $Id$
#

MAINTAINER=	sada@FreeBSD.ORG

FILESDIR=	${BASEDIR}/files

BASEDIR=	${.CURDIR}/../netscape45-communicator
BROWSER=	navigator
NSUBDIR=	lib/netscape

.include	"${BASEDIR}/Makefile"
