# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.51
# Date created:		29 Dec 1998
# Whom:			sada@FreeBSD.ORG
#
# $Id$
#

BROKEN=		REPOSITORY COPIED

MAINTAINER=	sada@FreeBSD.ORG

FILESDIR=	${BASEDIR}/files

BASEDIR=	${.CURDIR}/../netscape45-communicator
BROWSER=	navigator
BROWSER_BIN=	navigator-4.5.1.bin
NSUBDIR=	lib/netscape

.include	"${BASEDIR}/Makefile"
