# $Id$
#

    SUBDIR += SSLeay
    SUBDIR += donkey
    SUBDIR += fwtk
    SUBDIR += libident
    SUBDIR += p5-Crypt-DES
    SUBDIR += p5-Crypt-IDEA
    SUBDIR += p5-MD5
    SUBDIR += p5-PGP
    SUBDIR += pgp
    SUBDIR += pidentd
    SUBDIR += ssh
    SUBDIR += tcp_wrapper
    SUBDIR += vscan
    SUBDIR += xinetd

.include <bsd.port.subdir.mk>
