# $Id$
#

    SUBDIR += SSLeay
    SUBDIR += cfs
    SUBDIR += cops
    SUBDIR += crack
    SUBDIR += donkey
    SUBDIR += fwtk
    SUBDIR += john
    SUBDIR += libident
    SUBDIR += nat
    SUBDIR += p5-Authen-Radius
    SUBDIR += p5-Crypt-DES
    SUBDIR += p5-Crypt-IDEA
    SUBDIR += p5-MD5
    SUBDIR += p5-PGP
    SUBDIR += pgp
    SUBDIR += pidentd
    SUBDIR += rsaref
    SUBDIR += ssh
    SUBDIR += skip
    SUBDIR += sudo
    SUBDIR += super
    SUBDIR += swatch
    SUBDIR += tcp_wrapper
    SUBDIR += tripwire
    SUBDIR += vscan
    SUBDIR += xinetd

.include <bsd.port.subdir.mk>
