# $Id$
#

    SUBDIR += SSLeay
    SUBDIR += fwtk
    SUBDIR += libident
    SUBDIR += pgp
    SUBDIR += pidentd
    SUBDIR += ssh
    SUBDIR += tcp_wrapper
    SUBDIR += xinetd

.include <bsd.port.subdir.mk>
