# New ports collection makefile for:    spider
# Version required:     1.1
# Date created:         2 Oct 1995
# Whom:                 se
#
# $Id$
#

DISTNAME=	spider
PKGNAME=	spider-1.1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.uni-koeln.de/windows/xcontrib/

MAINTAINER=	asami@FreeBSD.ORG

USE_IMAKE=	yes
INSTALL_TARGET=	install install.doc

.include <bsd.port.mk>
