# New ports collection makefile for:	kinput2-canna+sj3
# Version required:	2.0p4
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $Id$
#

PKGNAME=	ja-kinput2-canna+sj3-2.0.4
CANNA=		yes
SJ3=		yes

MASTERDIR=	${.CURDIR}/../kinput2-wnn4/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
