# New ports collection makefile for:	mpd
# Version required:			2.0b1
# Date created:				25 Feb 1999
# Whom:					Archie Cobbs
#
# $Id$
#

DISTNAME=	mpd-2.0b1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.whistle.com/pub/archie/mpd/

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	files/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
