# New ports collection makefile for:	ctwm
# Version required:	3.2 patchlevel 1
# Date created:		13 November 1994
# Whom:			torstenb
#
# $Id$
#

DISTNAME=	ctwm-3.3
MASTER_SITES=	ftp://ftp.x.org/contrib/window_managers/
USE_IMAKE=	YES
EXTRACT_SUFX=	.tar.Z
LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

.include <bsd.port.mk>
