# New ports collection makefile for:	ctwm
# Version required:	3.4
# Date created:		13 November 1994
# Whom:			torstenb
#
# $Id$
#

DISTNAME=	ctwm-3.5beta3
PKGNAME=	ctwm-3.5b3
CATEGORIES=	x11
MASTER_SITES=	ftp://slhp1.epfl.ch/pub/ \

MAINTAINER=	torstenb@FreeBSD.ORG

LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

BROKEN=		upgraded and not available on master site anymore
USE_IMAKE=	yes

.include <bsd.port.mk>
