# New ports collection makefile for:	ctwm
# Version required:	3.4
# Date created:		13 November 1994
# Whom:			torstenb
#
# $Id$
#

DISTNAME=	ctwm-3.4pl2
PKGNAME=	ctwm-3.4.2
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	window_managers

MAINTAINER=	torstenb@FreeBSD.ORG

LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

.include <bsd.port.mk>
