# New ports collection makefile for:   qstat
# Version required:    2.0b
# Date created:        28 May 1998
# Whom:                Daniel O'Connor <darius@dons.net.au>
#
# $Id$
#

DISTNAME=	qstat20b
PKGNAME=        qstat-2.0b
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.activesw.com/pub/quake/

MAINTAINER=	darius@dons.net.au

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/qstat ${PREFIX}/bin

.include <bsd.port.mk>
