# New ports collection makefile for:	Xserver for Mach64 with X True Type
# Version required:	1.0
# Date created:		15 April 1998
# Whom:			Taguchi Takeshi <taguchi@tohoku.iij.ad.jp>
#
# $Id$
#

DISTNAME=	xc
PKGNAME=	xtt-Mach64-1.0
CATEGORIES=	x11

SERVER=		XF86_Mach64

.include "${.CURDIR}/../XttXF86srv-common/Makefile"
