# New ports collection makefile for:	yale-tftpd
# Version required:	3.0
# Date created:		Oct 8, 1994
# Whom:			pst
#
# $Id$
#

DISTNAME=	yale-tftpd-3.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.cert.dfn.de/pub/tools/net/yale-tftpd/

MAINTAINER=	ports@FreeBSD.org

BROKEN_ELF=	classes/libclasses.a

NO_WRKSUBDIR=

.include <bsd.port.mk>
