# New ports collection makefile for:	lupe
# Version required:	0.07
# Date created:		4 February 1998
# Whom:			FURUSAWA,Kazuhisa <kazu@jp.freebsd.org>
#
# $Id$
#

DISTNAME=	lupe007
PKGNAME=	lupe-0.07
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.eos.hokudai.ac.jp/pub/X11/contrib/misc/

MAINTAINER=	kazu@jp.freebsd.org

WRKSRC=		${WRKDIR}/lupe
USE_GMAKE=	yes
USE_IMAKE=	yes
XMKMF=		xmkmf
MAN1=		lupe.1

.include <bsd.port.mk>
