# New ports collection makefile for:	m4
# Version required:     1.4
# Date created:		25 October 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=       m4-1.4
CATEGORIES=	devel
MASTER_SITES=   ${MASTER_SITE_GNU}

GNU_CONFIGURE=yes
CONFIGURE_ARGS= --program-prefix=g

.include <bsd.port.mk>
