# New ports collection makefile for:	m4
# Version required:     1.4
# Date created:		25 October 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=       m4-1.4
CATEGORIES+=	development programming
MASTER_SITES=   ftp://gatekeeper.dec.com/pub/GNU/ \
		ftp://prep.ai.mit.edu/pub/gnu/

GNU_CONFIGURE=yes
CONFIGURE_ARGS= --program-prefix=g --prefix=${PREFIX}

.include <bsd.port.mk>
