# New ports collection makefile for:	m4
# Version required:	1.3
# Date created:		25 October 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=	m4-1.3
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu/
EXTRACT_SUFX=.tar.gz
HAS_CONFIGURE=yes

.include <bsd.port.mk>
