# New ports collection makefile for:	jpeg
# Version required:	5a
# Date created:		6 November 1994
# Whom:			smace
#
# $Id$
#

DISTNAME=	jpegsrc.v5a
PKGNAME=	jpeg-5a
GNU_CONFIGURE=	yes
MASTER_SITES=	ftp://ftp.uu.net/graphics/jpeg/ ftp://ftp.netcom.com/pub/tgl/uunet/
WRKSRC=		${WRKDIR}/jpeg-5a

.include <bsd.port.mk>
