# New ports collection makefile for:    s3mod
# Version required:     1.08A
# Date created:         9 March 1995
# Whom:                 ugen
#
# $Id$
#

DISTNAME=       s3mod-v1.08A
PKGNAME=	s3mod-1.08a
CATEGORIES=	audio
MASTER_SITES=   ${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/sound/players
DISTFILES=      s3mod-v1.08A.tar.gz

MAINTAINER=	ugen@FreeBSD.org

INSTALL_TARGET= install 

.include <bsd.port.mk>
