# $Id$
#
# RESTRICTED: xmcd (needs Motif, xmcd itself isn't restricted)
#
# BROKEN: gmod
# BROKEN: rplay (can't connect to master site)
#

SUBDIR= gsm maplay nas playmidi rsynth s3mod sox tracker xcd xcdplayer

.include <bsd.port.subdir.mk>
