# $Id$
#
# RESTRICTED: xmcd (needs Motif, xmcd itself isn't restricted)
#
# BROKEN: gmod
# BROKEN: rsynth (can't find a master site)
#

   SUBDIR += gsm
   SUBDIR += maplay
   SUBDIR += nas
   SUBDIR += playmidi
   SUBDIR += rplay
   SUBDIR += s3mod
   SUBDIR += sox
   SUBDIR += tracker
   SUBDIR += xcd
   SUBDIR += xcdplayer
   SUBDIR += xmix

.include <bsd.port.subdir.mk>
