# $Id$
#

    SUBDIR += gmod
    SUBDIR += gsm
    SUBDIR += maplay
    SUBDIR += nas
    SUBDIR += playmidi
    SUBDIR += radio
    SUBDIR += rplay
    SUBDIR += rsynth
    SUBDIR += s3mod
    SUBDIR += sox
    SUBDIR += tracker
    SUBDIR += workman
    SUBDIR += xcd
    SUBDIR += xcdplayer
    SUBDIR += xmcd
    SUBDIR += xmix

.include <bsd.port.subdir.mk>
