# New ports collection makefile for:   gtkfind
# Version required:    0.9
# Date created:        28 Sept 1998
# Whom:                Bill Fumerola <billf@chc-chimes.com>
#
# $Id$
#

DISTNAME=	gtkfind-0.9
CATEGORIES=	misc
MASTER_SITES=	http://www.oz.net/~mattg/

MAINTAINER=	billf@FreeBSD.org

LIB_DEPENDS=	gtk.1:${PORTSDIR}/x11-toolkits/gtk

ALL_TARGET=	gtkfind

MAN1=		gtkfind.1

.include <bsd.port.mk>
