# $Id$
#
# RESTRICTED: hpack.non-usa_only
# RESTRICTED: unzip.with_encryption
# RESTRICTED: zip.with_encryption
#

SUBDIR= arc gshar+gunshar ha lha unarj unrar unzip zip zoo

.include <bsd.port.subdir.mk>
