# $Id$
#

    SUBDIR += arc
    SUBDIR += gshar+gunshar
    SUBDIR += ha
    SUBDIR += hpack.non-usa.only
    SUBDIR += lha
    SUBDIR += rar
    SUBDIR += unarj
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += unzip.with_encryption
    SUBDIR += zip
    SUBDIR += zip.with_encryption
    SUBDIR += zoo

.include <bsd.port.subdir.mk>
