# New ports collection makefile for:    xtestpicture
# Version required:     1.1
# Date created:         11 March 1997
# Whom:                 joerg
#
# $Id$
#

DISTNAME=       xtestpicture-1.1
CATEGORIES=	x11
MASTER_SITES=   ${MASTER_SITE_LOCAL}

MAINTAINER=     joerg@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
