# New ports collection makefile for:	xsysstats
# Version required:	1.34
# Date created:		12 December 1994
# Whom:			asami
#
# $Id$
#

DISTNAME=	xsysstats1.34
PKGNAME=	xsysstats-1.34
CATEGORIES+=	utilities x11
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/utilities/

MAINTAINER=	asami@FreeBSD.ORG

USE_IMAKE=	yes

.include <bsd.port.mk>
