# New ports collection makefile for:    lynx
# Version required:     2.3
# Date created:         5 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       lynx2-3
EXTRACT_SUFX=   .tar.Z
MASTER_SITES=   ftp://ftp2.cc.ukans.edu/pub/lynx/

.include <bsd.port.mk>
