# New ports collection makefile for: GP + Japanese treatment
# Version required:	2.5
# Date created:		15 April 1997
# Whom:			Kiriyama Kazuhiko<kiri@kiri.toba-cmt.ac.jp>
#
# $Id$
#

PKGNAME=	ja-gp-2.5
CATEGORIES=	japanese

LANGUAGE=	Japanese

.include "${.CURDIR}/../../print/gp/Makefile"
