# New ports collection makefile for: English PK fonts at 240dpi
# Version required:	?
# Date created:		06 Nov 1998
# Whom:			Satoshi Asami <asami@freebsd.org>
#
# $Id$
#

RESOLUTION=	240
FILESDIR=	${.CURDIR}/../pkfonts300/files
PKGDIR=		${.CURDIR}/../pkfonts300/pkg

.include "${.CURDIR}/../pkfonts300/Makefile"
