# New ports collection makefile for: English PK fonts at 240dpi
# Version required:	?
# Date created:		06 Nov 1998
# Whom:			Satoshi Asami <asami@FreeBSD.org>
#
# $Id$
#

RESOLUTION=	240
MASTERDIR=	${.CURDIR}/../pkfonts300

.include	"${MASTERDIR}/Makefile"
