# $Id$
#
    SUBDIR += exodus
    SUBDIR += gdbm
    SUBDIR += gnats
    SUBDIR += msql
    SUBDIR += msqlperl
    SUBDIR += p5-DBD-mSQL
    SUBDIR += p5-DBI
    SUBDIR += p5-Msql
    SUBDIR += p5-Pg
    SUBDIR += postgres95
    SUBDIR += xfsql

.include <bsd.port.subdir.mk>
