# $Id$
#
    SUBDIR += db
    SUBDIR += exodus
    SUBDIR += gdbm
    SUBDIR += gnats
    SUBDIR += msql
    SUBDIR += msql-beta
    SUBDIR += mysql
    SUBDIR += p5-DBD-mSQL
    SUBDIR += p5-DBD-mysql
    SUBDIR += p5-DBD-Pg
    SUBDIR += p5-DBI
    SUBDIR += p5-Msql
    SUBDIR += p5-Mysql
    SUBDIR += p5-Pg
    SUBDIR += postgresql
    SUBDIR += typhoon
    SUBDIR += xfsql

.include <bsd.port.subdir.mk>
