# New ports collection makefile for:	chard
# Version required:	3.6
# Date created:		24 April 1995
# Whom:			Satoshi Asami
#
# $Id$
#

DISTNAME=	chord
PKGNAME=	chord-3.6
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.ORG

.include <bsd.port.mk>
