# New ports collection makefile for:    xboard
# Version required:     3.2 patchlevel 0
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xboard-3.2.pl0
MASTER_SITES=	ftp://ftp.x.org/contrib/games/
CATEGORIES+=	games
HAS_CONFIGURE=  yes
STRIP=
CONFIGURE_ARGS= --prefix=${PREFIX}

.include <bsd.port.mk>
