# New ports collection makefile for:    xboard
# Version required:     3.6.0
# Date created:         5 Jan 1997
# Whom:                 xaa@stack.nl
#
# $Id$
#

DISTNAME=       xboard-3.6.0
PKGNAME=	xboard-3.6.0
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GNU}

MAINTAINER=	xaa@stack.nl

GNU_CONFIGURE=  yes
CONFIGURE_ARGS= --prefix=${PREFIX}
STRIP=
MAN6=		xboard.6 cmail.6 zic2xpm.6

.include <bsd.port.mk>
