# New ports collection makefile for:	GNU make
# Version required:     3.75
# Date created:		11 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       make-3.75
PKGNAME=        gmake-3.75
CATEGORIES+=	devel
MASTER_SITES=   ftp://prep.ai.mit.edu/pub/gnu/ \
		ftp://ftp.uu.net/systems/gnu/

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
