# New ports collection makefile for:	GNU make
# Version required:	3.71
# Date created:		11 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	make-3.71
HAS_CONFIGURE=	yes
HOME_LOCATION=	ftp://prep.ai.mit.edu/pub/gnu/make-3.71.tar.gz

.include <bsd.port.mk>
