# New ports collection makefile for:	xroach
# Version required:	4.4BSD-Lite
# Date created:		22 December 1995
# Whom:			markm
#
# $Id$
#

DISTNAME=	xroach
PKGNAME=	xroach-4.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.cdrom.com/pub/bsd-sources/4.4BSD-Lite/usr/src/games/

MAINTAINER=	markm@FreeBSD.ORG

USE_X_PREFIX=	yes
IGNOREFILES=	${DISTFILES}
WRKSRC=		${WRKDIR}/pub/bsd-sources/4.4BSD-Lite/usr/src/games/xroach

.include <bsd.port.mk>
