# New ports collection makefile for:	xgrasp
# Version required:     1.7d
# Date created:         23 July 1995
# Whom:                 asami
#
# $Id$
#

DISTNAME=	xgrasp.1.7d
PKGNAME=	xgrasp-1.7d
CATEGORIES=	graphics x11
MASTER_SITES=	ftp://qiclab.scn.rain.com/pub/X11/	\
		ftp://ftp.cs.ubc.ca/mirror1/x-contrib.R5/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	asami@FreeBSD.ORG

USE_IMAKE=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
