# New ports collection makefile for:    pgpsendmail
# Version required:     1.4
# Date created:         20 Jan 1995
# Whom:                 ache
#
# $Id$
#

DISTNAME=       PGPsendmail-v1.4
MASTER_SITES=   ftp://ftp.dhp.com/pub/crypto/pgp/PGPsendmail/
WRKSRC=         ${WRKDIR}/pgpsendmail
INSTALL_TARGET= all_install

.include <bsd.port.mk>
