#! /bin/sh

# $FreeBSD$
USER=operator
GROUP=${USER}

case $2 in
POST-INSTALL)
	echo "Modifying permissions on ${PKG_PREFIX}/libexec/amanda"
	/usr/sbin/chown ${USER}:${GROUP} ${PKG_PREFIX}/libexec/amanda
	/bin/chmod 510 ${PKG_PREFIX}/libexec/amanda
	/usr/sbin/chown ${USER}:${GROUP} ${PKG_PREFIX}/libexec/amanda/*
	/bin/chmod 4550 ${PKG_PREFIX}/libexec/amanda/*
	;;
esac
