# New ports collection makefile for:	Linux-style colorized `ls'
# Version required:			3.12.0.2 (GNU fileutils 3.12)
# Date created:				06 January 1996
# Whom:					bmc@WillsCreek.COM
#
# $Id$
#

DISTNAME=	fileutils-3.16
PKGNAME=	gnuls-3.16
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	fileutils

MAINTAINER=	bmc@WillsCreek.COM

GNU_CONFIGURE=	yes
MAN1=		gnuls.1 dircolors.1

.include <bsd.port.mk>
