# New ports collection makefile for:	blt
# Version required:	1.7
# Date created:		14 December 1994
# Whom:			wollman
#
# $Id$
#

DISTNAME=	blt-1.7
DISTFILES=	BLT-1.7.tar.gz
MASTER_SITES=	ftp://ftp.aud.alcatel.com/tcl/extensions/
DEPENDS=	${PORTSDIR}/x11/tk
GNU_CONFIGURE=	yes
ALL_TARGET=	all sharedlib

.include <bsd.port.mk>

