# New ports collection makefile for:	xfm
# Version required:	1.3
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $Id$
#

DISTNAME=	xfm-1.3
DISTFILES=	xfm-1.3.tar.gz
USE_IMAKE=	yes
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/applications/
LIB_DEPENDS=    Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

.include <bsd.port.mk>
