# $Id$
#

    SUBDIR += Mosaic         # requires Motif
    SUBDIR += analog
    SUBDIR += apache
    SUBDIR += arena
    SUBDIR += ashe           # requires Motif
    SUBDIR += cached
    SUBDIR += chimera
    SUBDIR += comline
    SUBDIR += gn
    SUBDIR += harvest
    SUBDIR += javac_netscape
    SUBDIR += jdk
    SUBDIR += kaffe
    SUBDIR += libwww
    SUBDIR += linemode
    SUBDIR += lynx
    SUBDIR += mapedit
    SUBDIR += netscape2
    SUBDIR += netscape3
    SUBDIR += slang-lynx
    SUBDIR += squid
    SUBDIR += tkHTML
    SUBDIR += tkWWW
    SUBDIR += w3c_httpd
    SUBDIR += weblint
    SUBDIR += wn
    SUBDIR += wwwcount
    SUBDIR += wwwish

.include <bsd.port.subdir.mk>
