# New ports collection makefile for:	xanim
# Version required:     2.70.1
# Date created:         Sat Nov 5 11:43:03 PST 1994
# Whom:                 piero
#
# $Id$
#

DISTNAME=       xanim2701
PKGNAME=        xanim-2.70.1
CATEGORIES+=	graphics x11
MASTER_SITES=	ftp://ftp.portal.com/pub/podlipec/

USE_IMAKE=	is_set

.include <bsd.port.mk>
