# New ports collection makefile for:    xephem
# Version required:     3.0
# Date created:         Thu Aug  1 09:10:22 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $Id$
#

DISTNAME=	xephem_3.0
PKGNAME=	xephem-3.0
CATEGORIES=	astro
MASTER_SITES=	ftp://iraf.noao.edu/contrib/xephem/xephem_3.0/

MAINTAINER=	erich@FreeBSD.org

REQUIRES_MOTIF=	yes

USE_IMAKE=	yes

.include <bsd.port.mk>
