# $Id$
#

    SUBDIR += Canna
    SUBDIR += Wnn
    SUBDIR += chimera
    SUBDIR += gawk
    SUBDIR += grep
    SUBDIR += groff
    SUBDIR += gxditview
    SUBDIR += kinput2-canna
    SUBDIR += kinput2-canna+wnn
    SUBDIR += kinput2-wnn
    SUBDIR += kon
    SUBDIR += kterm
    SUBDIR += less
    SUBDIR += mh
    SUBDIR += mule-canna
    SUBDIR += mule-wnn
    SUBDIR += nethack
    SUBDIR += netscape.language
    SUBDIR += nkf
    SUBDIR += ptex
    SUBDIR += sed
    SUBDIR += tcl
    SUBDIR += tk

.include <bsd.port.subdir.mk>
