# $Id$
#
# restricted: none
#
# broken: none
#
SUBDIR= Canna Wnn gawk grep groff gxditview \
	kinput2-canna kinput2-canna+wnn kinput2-wnn \
	kterm less nkf mh mule-canna mule-wnn sed tcl tk

.include <bsd.port.subdir.mk>
