# New ports collection makefile for:	xzip
# Version required:			1.8.0
# Date created:				28 June 1998
# Whom:					Matthew Hunt <mph@FreeBSD.org>
#
# $Id$
#

DISTNAME=		xzip180
PKGNAME=		xzip-1.8.0
CATEGORIES=		games
MASTER_SITES=   	ftp://ftp.gmd.de/if-archive/infocom/interpreters/zip/
EXTRACT_SUFX=		.tar.Z

MAINTAINER=		mph@freebsd.org

WRKSRC=			${WRKDIR}/xzip
ALL_TARGET=

USE_XLIB=		yes

MAN1=			xzip.1

.include <bsd.port.mk>
