# New ports collection makefile for:	freeciv
# Version required:	1.7.2
# Date created:		Jun 20 1997
# Whom:			ada@bsd.org
#
# $Id$
#

DISTNAME=	freeciv-1.7.2
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.freeciv.org/pub/freeciv/

MAINTAINER=	ada@bsd.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

HAS_CONFIGURE=	yes

.include <bsd.port.mk>
