# Ports collection makefile for:    dhcp
# Version required:     ISC-DHCP-BETA-0
# Date created:         7 Mar 1996
# Whom:                 se
#
# $Id$
#

DISTNAME=       DHCPD-BETA-5.14
PKGNAME=	isc-dhcp-b5.14
CATEGORIES=	net
MASTER_SITES=   ftp://ftp.vix.com/pub/dhcp/

MAINTAINER=	se@FreeBSD.ORG
HAS_CONFIGURE=	yes

MAN5=		dhcpd.conf.5${ZEXTENSION}
MAN8=		dhcpd.8${ZEXTENSION}

.include <bsd.port.mk>
