# New ports collection makefile for:    prcs
# Version required:     1.2.4
# Date created:         17 Sep 96
# Whom:                 jmacd@FreeBSD.ORG
#
# $Id$
#

DISTNAME= 	prcs-1.2.4
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.xcf.berkeley.edu/pub/prcs/

MAINTAINER=	jmacd@FreeBSD.ORG

USE_GMAKE=	yes
HAS_CONFIGURE=	yes
MAN1=		prcs.1

.include <bsd.port.mk>
