# New ports collection Makefile for: rxvt
# Version required:	2.45
# Date created:         5th December 1994
# Whom:                 gpalmer@FreeBSD.org
#
# $Id$
#

DISTNAME=	rxvt-2.4.5
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.math.fu-berlin.de/pub/rxvt/

MAINTAINER=	ports@FreeBSD.ORG

USE_X_PREFIX=	yes
GNU_CONFIGURE=  yes
MAN1=		rxvt.1

.include <bsd.port.mk>
