# New ports collection makefile for:    trans
# Version required:     1.11
# Date created:         6 May 1996
# Whom:                 ache@astral.msk.su
#
# $Id$
#

DISTNAME=       trans111
PKGNAME=        trans-1.11
CATEGORIES=     misc russian
MASTER_SITES=   ftp://ftp.informatik.uni-erlangen.de/pub/doc/ISO/charsets/

MAINTAINER=     ache@astral.msk.su

.include <bsd.port.mk>
