# New ports collection makefile for:	oleo
# Version required:	1.6
# Date created:		3 September 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=	oleo-1.6
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu/
EXTRACT_SUFX=.tar.gz

HAS_CONFIGURE=yes

.include <bsd.port.mk>
