# New ports collection makefile for:	pine
# Version required:	3.90
# Date created:		03 September 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=	oleo-1.6
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu
EXTRACT_SUFX=.tar.gz
HAS_CONFIGURE=yes

.include <bsd.port.mk>
