# New ports collection makefile for:	imm
# Version required:	3.3
# Date created:		13 October 1994
# Whom:			wollman
#
# $Id$
#

DISTNAME=	imm-3.3
CATEGORIES+=	net
MASTER_SITES=	ftp://ftp.ucs.ed.ac.uk/pub/videoconference/imm/
DISTFILES=	imm.src.tar.Z

LIB_DEPENDS=	tk\\.3\\.:${PORTSDIR}/x11/tk

WRKSRC=		${WRKDIR}/src

.include <bsd.port.mk>
