# New ports collection makefile for:	msql
# Version required:	1.0.5
# Date created:		14 January 1995
# Whom:			mr (original)
#
# $Id$
#

DISTNAME=	msql-1.0.5
CATEGORIES+=	databases
MASTER_SITES=	ftp://bond.edu.au/pub/Minerva/msql/
EXTRACT_SUFX=	.tar.gz

IS_INTERACTIVE=	YES
PREFIX=		/usr/local/Minerva

.include <bsd.port.mk>

