# New ports collection makefile for:	msql
# Version required:	1.0
# Date created:		?
# Whom:			mr (original)
#
# $Id$
#

DISTNAME=	msql-1.0.5
EXTRACT_SUFX=	.tar.gz
MASTER_SITES=	ftp://bond.edu.au/pub/Minerva/msql/
CATEGORIES+=	databases
IS_INTERACTIVE=	YES
PREFIX=		/usr/local/Minerva

.include <bsd.port.mk>

