# New ports collection makefile for:	fetchmail
# Version required:	2.3.0
# Date created:		26 Oct 1996
# Whom:			Ville Eerola <ve@sci.fi>
#
# $Id$
#

DISTNAME=	fetchmail-2.3
PKGNAME=	fetchmail-2.3.0
CATEGORIES=	mail
MASTER_SITES=	ftp://locke.ccil.org/pub/esr/

MAINTAINER=	ve@sci.fi

GNU_CONFIGURE=	yes
CONFIGURE_ENV+=	LDFLAGS="${CFLAGS}"
MAN1=		fetchmail.1

.include <bsd.port.mk>
