# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.07
# Date created:		13 Mar 1998
# Whom:			sada
#
# $Id$
#

MAINTAINER=	sada@FreeBSD.ORG

MASTERDIR=	${.CURDIR}/../netscape4-communicator
PKGDIR=		${.CURDIR}/pkg

BROKEN=		www/netscape4-navigator was upgraded to 4.08
BROWSER_NAME=	navigator
MANFILE=	${.CURDIR}/files/${MAN1}

.include	"${MASTERDIR}/Makefile"
