# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.08
# Date created:		13 Mar 1998
# Whom:			sada@FreeBSD.ORG
#
# $Id$
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator

MAINTAINER=	sada@FreeBSD.ORG

BROWSER=	navigator
PATCHDIRS=	${.CURDIR}/patches

.include	"${MASTERDIR}/Makefile"
