# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.07
# Date created:		13 Mar 1998
# Whom:			sada
#
# $Id$
#

MAINTAINER=	sada@e-mail.ne.jp

MASTERDIR=	${.CURDIR}/../netscape4-communicator
PKGDIR=		${.CURDIR}/pkg

BROWSER_NAME=	navigator
MANFILE=	${.CURDIR}/files/${MAN1}

.include	"${MASTERDIR}/Makefile"
