# New ports collection makefile for:	xscavenger
# Version required:	1.3
# Date created:		19 Feb 1998
# Whom:			eivind
#
# $Id$
#

DISTNAME=	xscavenger-1.3
DISTFILES=	xscavenger-13.tgz
CATEGORIES=	games
MASTER_SITES=	http://www.epyx.com/dash/
WRKSRC=		${WRKDIR}/${DISTNAME}/src
USE_IMAKE=	yes
NO_INSTALL_MANPAGES=yes

MAINTAINER=	eivindFreeBSD.org

.include <bsd.port.mk>
