# New ports collection makefile for:	xlockmore
# Version required:     3.13
# Date created:		9 November 1994
# Whom:			smace
#
# $Id$
#

DISTNAME=       xlockmore-3.13
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	ports@freebsd.org

LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

.include <bsd.port.mk>
