# New ports collection makefile for:    playmidi
# Version required:     1.1
# Date created:         27 Feb 1995
# Whom:                 ache
#
# $Id$
#

DISTNAME=       playmidi
PKGNAME=	playmidi-1.1
CATEGORIES+=	audio
MASTER_SITES=   ftp://sunsite.unc.edu/pub/Linux/apps/sound/players/
DISTFILES=      playmidi-1.1.tar.gz

MAINTAINER=     ache@FreeBSD.ORG

.include <bsd.port.mk>
