# New ports collection makefile for:    tracker
# Version required:     4.19
# Date created:         27 Feb 1995
# Whom:                 ache
#
# $Id$
#

DISTNAME=       playmidi
DISTFILES=      playmidi-1.1.tar.gz
MASTER_SITES=   ftp://sunsite.unc.edu/pub/Linux/apps/sound/players/

.include <bsd.port.mk>
