# New ports collection makefile for:	pine
# Version required:	3.90
# Date created:		03 September 1994
# Whom:			mr
#
# $Id$
#

DISTNAME=	pine3.91
MASTER_SITES=	ftp://ftp.cac.washington.edu/pine/
EXTRACT_SUFX=.tar.Z

.include <bsd.port.mk>
