# New ports collection makefile for:	Blackbox
# Version required:	0.50.2
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $Id$
#

DISTNAME=	blackbox-0.50.2
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://balance.wiw.org/pub/blackbox/ \
		ftp://ftp.aist.com.ua/pub/unix/window_managers/blackbox/

MAINTAINER=	ports@FreeBSD.ORG

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
