# New ports collection makefile for:	Blackbox
# Version required:	0.33.6
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $Id$
#

DISTNAME=	blackbox-0.33.6
CATEGORIES=	x11
MASTER_SITES=	http://linux.wiw.org/blackbox/sources/

MAINTAINER=	ports@FreeBSD.ORG

USE_IMAKE=		yes

.include <bsd.port.mk>
