# New ports collection makefile for:	Blackbox
# Version required:	0.40.11
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $Id$
#

DISTNAME=	blackbox-0.40.11
CATEGORIES=	x11-wm
MASTER_SITES=	http://linux.wiw.org/blackbox/sources/

MAINTAINER=	ports@FreeBSD.ORG

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
