# $Id$
#

    SUBDIR += acs
    SUBDIR += chipmunk
    SUBDIR += felt
    SUBDIR += irsim
    SUBDIR += kaskade
    SUBDIR += magic
    SUBDIR += mars
    SUBDIR += pcb
    SUBDIR += spice
    SUBDIR += xcircuit

.include <bsd.port.subdir.mk>
