# New ports collection makefile for:	xarchie
# Version required:	2.0.9
# Date created:		24 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	xarchie-2.0.10
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/applications/
MASTER_SITES+=	ftp://ftp.funet.fi/pub/X11/contrib/applications/

USE_IMAKE=	yes
DEPENDS=	${PORTSDIR}/net/archie

.include <bsd.port.mk>
