# New ports collection makefile for:	xarchie
# Version required:	2.0.9
# Date created:		24 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	xarchie-2.0.9
USE_IMAKE=	yes
MASTER_SITES=	ftp://ftp.uu.net/networking/info-service/archie/clients/
EXTRACT_SUFX=	.tar.Z
DEPENDS_ON=	net/archie

.include <bsd.port.mk>
