# New ports collection makefile for:    stat
# Version required:     1.3
# Date created:         16 Februar 1996
# Whom:                 wosch
#
# $Id$

DISTNAME=       stat-1.3
CATEGORIES=	sysutils
MASTER_SITES=   ${MASTER_SITE_LOCAL}

MAINTAINER=     wosch@FreeBSD.org

.include <bsd.port.mk>
