# New ports collection makefile for:	ja-tcsh NLS catalog (Multi)
# Version required:	6.08.00
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.ORG>
#
# $Id$
#

DISTNAME=	tcsh-6.08.00.add
PKGNAME=	ja-tcsh-nls-multi-6.08.00
CATEGORIES=	japanese shells
MASTER_SITES=	http://www2.wbs.ne.jp/~znc/tcsh/

MAINTAINER=	issei@jp.FreeBSD.ORG

PLIST=		../tcsh-nls-generic/pkg/PLIST
NLSSRC=		${DISTNAME}/nls/ja.multi

.include "../tcsh-nls-generic/Makefile"
