# New ports collection makefile for:	team
# Version required:	3.1 (From the RCS Id line of team.c)
# Date created:		1 July 1995
# Whom:			joerg
#
# $Id$
#

DISTNAME=	team-3.1
CATEGORIES+=	misc
MASTER_SITES=	ftp://freefall.freebsd.org/pub/FreeBSD/LOCAL_PORTS/

MAINTAINER=	joerg@FreeBSD.org

.include <bsd.port.mk>
