# New ports collection makefile for:  rshell
# Version required:    1.0
# Date created:        1997/06/09
# Whom:                wosch
#
# $Id$


DISTNAME=      rshell-1.0
CATEGORIES=    misc
MASTER_SITES=  ${MASTER_SITE_LOCAL}

MAINTAINER=    wosch@FreeBSD.ORG

.include <bsd.port.mk>
