# New ports collection makefile for:	bcc
# Version required:	"1995 Mar 12 10:29 UTC"
# Date created:		26 March 1995
# Whom:			joerg
#
# $Id$
#

DISTNAME=	sdcc-2.1.8Ma
PKGNAME=	sdcc-2.1.8
CATEGORIES=	devel lang
MASTER_SITES=	http://www.geocities.com/ResearchTriangle/Forum/1353/

MAINTAINER=	ambrisko@whistle.com

WRKSRC=         ${WRKDIR}/sdcc218Ma
GNU_CONFIGURE=	yes
USE_GMAKE=      yes
ALL_TARGET=	dep all

.include <bsd.port.mk>
