# Ports collection makefile for:    netatalk
# Version required:     netatalk-1.4b2
# Date created:         23 Jul 1997
# Whom:                 stb
#
# $Id$
#

DISTNAME=       netatalk-1.4b2
CATEGORIES=	net print
MASTER_SITES=   ftp://terminator.rs.itd.umich.edu/unix/netatalk/

MAINTAINER=	stb@freebsd.org

NOMANCOMPRESS=	true
# XXX this is a hack to make the .so-included
# man pages work.

.include <bsd.port.mk>
