# New ports collection makefile for:	xtoolwait
# Date created:		31 May 1997
# Whom:			jonny
#
# $Id$
#

DISTNAME=	xtoolwait-1.1
CATEGORIES=    x11
MASTER_SITES=	ftp://ftp.x.org/contrib/utilities/		\
		ftp://ftp.hacom.nl/pub/users/richard/

USE_IMAKE=	yes
MAN1=		xtoolwait.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
