# New ports collection makefile for:    ncftp2
# Version required:     2.0.3
# Date created:         4 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       ncftp-2.0.3
EXTRACT_SUFX=   .tgz
MASTER_SITES=   ftp://ftp.cs.unl.edu/pub/ncftp/
CATEGORIES+=	networking
GNU_CONFIGURE=  YES

.include <bsd.port.mk>
