# New ports collection makefile for:	Xserver for SVGA with X True Type
# Version required:	1.0
# Date created:		15 April 1998
# Whom:			Taguchi Takeshi <taguchi@tohoku.iij.ad.jp>
#
# $Id$
#

DISTNAME=	xc
PKGNAME=	xtt-SVGA-1.0
CATEGORIES=	x11

MAINTAINER=	taguchi@tohoku.iij.ad.jp

SERVER=		XF86_SVGA

.include "${.CURDIR}/../XttXF86srv-common/Makefile"

