# New ports collection makefile for:	GNU emacs
# Version required:	19.25
# Date created:		20 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	emacs-19.25
USE_GMAKE=	yes
HAS_CONFIGURE=	yes
CONFIGURE_ARGS=	i386--freebsd
HOME_LOCATION=	ftp://prep.ai.mit.edu/pub/gnu/emacs-19.25.tar.gz

.include <bsd.port.mk>
