# New ports collection makefile for:	xqf
# Version required:			0.8.7.2
# Date created:				08 February 1999
# Whom:					steve farrell
#
# $Id$
#

DISTNAME=	xqf-0.8.99.1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.linuxgames.com/xqf/

MAINTAINER=	steve@farrell.org

RUN_DEPENDS=	qstat:${PORTSDIR}/games/qstat
LIB_DEPENDS=    gtk12:${PORTSDIR}/x11-toolkits/gtk12

USE_GMAKE=	yes

.include <bsd.port.mk>
