# New ports collection makefile for:	xbl
# Version required:	1.0h
# Date created:		May 25 1997
# Whom:			pgs (original)
#
# $Id$
#

DISTNAME=	xbl-1.0h
CATEGORIES=	games
MASTER_SITES=	ftp://ftp710.univ-lyon1.fr/pub/xbl/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	giffunip@asme.org

USE_X_PREFIX=	yes
HAS_CONFIGURE=	yes
MANN=		xbl.n

.include <bsd.port.mk>
