# New ports collection makefile for:	xboing
# Version required:	2.4
# Date created:		31 January 1995
# Whom:			janek
#
# $Id$

DISTNAME=	xboing2.4
PKGNAME=	xboing-2.4
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games

MAINTAINER=	janek@gaja.ipan.lublin.pl

LIB_DEPENDS=	Xpm.5:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
WRKSRC= ${WRKDIR}/xboing

.include <bsd.port.mk>
