# New ports collection makefile for:    xrisk
# Version required:     2.13
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xrisk-2.13
CATEGORIES+=	games
MASTER_SITES=   ftp://geocub.greco-prog.fr/pub/Games/
EXTRACT_SUFX=   .tar.Z

# We can't distribute the source or the package because of 
# the restrictive copyright.
NO_PACKAGE=	yes

.include <bsd.port.mk>
