# New ports collection makefile for:    xrisk
# Version required:     2.13
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xrisk-2.13
CATEGORIES=	games
MASTER_SITES=   ftp://geocub.greco-prog.fr/pub/Games/
EXTRACT_SUFX=   .tar.Z

USE_X11=	yes
RESTRICTED=	"Possible trademark infringement."

.include <bsd.port.mk>
