# New ports collection makefile for:    xchomp
# Version required:     1.1
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xrisk-2.13
MASTER_SITES=   ftp://geocub.greco-prog.fr/pub/Games/
CATEGORIES+=	games
EXTRACT_SUFX=   .tar.Z

.include <bsd.port.mk>
