# New ports collection makefile for:	emu
# Version required:	1.3
# Date created:		13 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	emu-1.3
MASTER_SITES=	ftp://ftp.x.org/contrib/applications

.include <bsd.port.mk>
