# New ports collection makefile for: YaTeX
# Version required:	1.66
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	ja-yatex-xemacs-1.66
CATEGORIES=	japanese print elisp

XEMACS-MULE=	yes

MASTERDIR=	${.CURDIR}/../../print/yatex
PLIST=		${.CURDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
