# New ports collection Makefile for: rxvt
# Version required:	2.45
# Date created:         5th December 1994
# Whom:                 gpalmer@FreeBSD.org
#
# $Id$
#

DISTNAME=	rxvt-2.4.7
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.math.fu-berlin.de/pub/rxvt/  \
		${MASTER_SITE_SUNSITE}  \
		ftp://ftp.math.fu-berlin.de/pub/rxvt/devel/
MASTER_SITE_SUBDIR= X11/terms

MAINTAINER=	ports@FreeBSD.ORG

USE_X_PREFIX=	yes
GNU_CONFIGURE=  yes
MAN1=		rxvt.1

.include <bsd.port.mk>
