# New ports collection makefile for:   xbat
# Version required:    1.10
# Date created:        30 January 1997
# Whom:                Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $Id$
#

DISTNAME=	xev110
PKGNAME=        xbat-1.10
CATEGORIES=     games
MASTER_SITES=   http://www.nemoto.ecei.tohoku.ac.jp/~wai/Xbat/

MAINTAINER=	Nakai@Mlab.t.u-tokyo.ac.jp

NO_CDROM=	Possible copyright infringement

USE_IMAKE=	yes
WRKSRC=		${WRKDIR}/Xev110
ALL_TARGET=	xbat

.include <bsd.port.mk>
