# New ports collection makefile for:    xcd
# Version required:     1.0
# Date created:         22 November 1994
# Whom:                 jmz
#
# $Id$
#

DISTNAME=	xcd-1.0
CATEGORIES+=	audio
MASTER_SITES=	ftp://ftp.obs-besancon.fr/pub/outgoing/

MAINTAINER=	jmz@FreeBSD.org

.include <bsd.port.mk>
