# New ports collection makefile for:    xcd
# Version required:     1.5
# Date created:         22 November 1994
# Whom:                 jmz
#
# $Id$
#

DISTNAME=	xcd-1.5
CATEGORIES+=	audio
MASTER_SITES=	ftp://ftp.obs-besancon.fr/pub/outgoing/

WRKSRC=		${WRKDIR}/xcd

MAINTAINER=	jmz@FreeBSD.org

RUN_DEPENDS=    wish4.1:${PORTSDIR}/x11/tk41

.include <bsd.port.mk>
