# New ports collection makefile for:	pdksh
# Version required:	5.1.3
# Date created:		23 December 1994
# Whom:			thomas@ghpc8.ihf.rwth-aachen.de
#
# $Id$
#

DISTNAME=	pdksh-5.1.3
CATEGORIES+=	shells
MASTER_SITES=	ftp://ftp.cs.mun.ca/pub/pdksh/

GNU_CONFIGURE=  yes

.include <bsd.port.mk>
