# New ports collection makefile for:	pdksh
# Version required:	5.2.13
# Date created:		23 May 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.ORG>
#
# $Id$
#

DISTNAME=	pdksh-5.2.13
CATEGORIES=	shells
MASTER_SITES=	ftp://ftp.cs.mun.ca/pub/pdksh/

MAINTAINER=	tg@FreeBSD.ORG

GNU_CONFIGURE=  yes
CONFIGURE_ENV=	LDSTATIC=-static
MAN1=		ksh.1

.include <bsd.port.mk>
