# New ports collection makefile for: pips for EPSON PM-760C
# Date created:        2000.08.04
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES?=	japanese print linux
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg/COMMENT
DESCR=		${.CURDIR}/pkg/DESCR
PRTYPE=		760

do-install:     # empty

.include "${MASTERDIR}/Makefile"
