# New ports collection makefile for:	zsh
# Version required:     	2.6 beta7
# Date created:			11 Feb. 1995
# Whom:				torstenb
#
# $Id$
#

DISTNAME=       zsh-2.6-beta7
PKGNAME=	zsh-2.6b7
CATEGORIES+=	shells
MASTER_SITES=   ftp://ftp.math.gatech.edu/pub/zsh/

MAINTAINER=	torstenb@FreeBSD.ORG

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
