# New ports collection makefile for:	xpm
# Version required:	3.4e
# Date created:		14 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	xpm-3.4e
CATEGORIES+=	graphics x11
MASTER_SITES=	ftp://avahi.inria.fr/pub/xpm/

USE_IMAKE=	yes
XMKMF=		xmkmf

.include <bsd.port.mk>
