# New ports collection makefile for:	xpm
# Version required:	3.4e
# Date created:		14 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	xpm-3.4e
USE_IMAKE=	yes
MASTER_SITES=	ftp://avahi.inria.fr/pub/xpm/
CATEGORIES+=	graphics x11
XMKMF=		xmkmf

.include <bsd.port.mk>
