# New ports collection makefile for:	xv
# Version required:	3.10
# Date created:		30 October 1994
# Whom:			smace
#
# $Id$
#

DISTNAME=	xv-3.10
USE_IMAKE=	yes
MASTER_SITES=	ftp://ftp.cis.upenn.edu/pub/xv/
DEPENDS=	${PORTSDIR}/x11/jpeg ${PORTSDIR}/x11/tiff
INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
