# New ports collection makefile for:    SWIG
# Version required:     1.1b5p1
# Date created:         19 April 1996
# Whom:                 jkh
#
# $Id$
#

DISTNAME=	swig1.1b5p1
PKGNAME=	swig-1.1b5
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cs.utah.edu/pub/beazley/SWIG/

MAINTAINER=	erich@FreeBSD.org

WRKSRC=		${WRKDIR}/SWIG1.1b5p1
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
