# New ports collection makefile for:	sup
# Version required:	<own lineage>
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	sup
PKGNAME=	sup-2.0
CATEGORIES+=	net
MASTER_SITES=	ftp://freefall.freebsd.org/pub/FreeBSD/LOCAL_PORTS/

MAINTAINER=	gibbs@FreeBSD.org

.include <bsd.port.mk>
