# New ports collection makefile for:	sup
# Version required:	<own lineage>
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=	sup
MASTER_SITES=	ftp://freefall.cdrom.com/pub/FreeBSD/LOCAL_PORTS/

.include <bsd.port.mk>
