# New ports collection makefile for:    xinvaders
# Version required:     1.1
# Date created:         3 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xinvaders
PKGNAME=	xinvaders-1.1
CATEGORIES+=	games
MASTER_SITES=	ftp://romulus.ucs.uoknor.edu/Linux/sunsite/games/x11/action/

USE_IMAKE=	yes

.include <bsd.port.mk>
