# New ports collection makefile for:    xinvaders
# Version required:     1.1
# Date created:         3 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xinvaders
PKGNAME=	xinvaders-1.1
CATEGORIES+=	games
MASTER_SITES=	ftp://sunsite.unc.edu/pub/Linux/games/x11/video/

USE_IMAKE=	yes

NO_CDROM=	yes	# "don't sell for profit"

.include <bsd.port.mk>
