# New ports collection makefile for:	uzap
# Version required:	1.0
# Date created:		19 Jun 1995
# Whom:			joerg
#
# $Id$
#

DISTNAME=	uzap
PKGNAME=	uzap-1.0
CATEGORIES+=	editors
MASTER_SITES=	ftp://ftp.germany.eu.net/pub/utils/uzap/

WRKSRC=		${WRKDIR}

# restrictive Copyright; the author is no longer reachable, however :-(
RESTRICTED=	"Restrictive copyright."

.include <bsd.port.mk>
