# New ports collection makefile for:	Mark Moraes malloc library
# Version required:	1.13??
# Date created:		11 January 1995
# Whom:			jkh
#
# $Id$
#

DISTNAME=	malloc
MASTER_SITES=	ftp.cs.toronto.edu:/pub/moraes/
CATEGORIES+=	development programming libraries

.include <bsd.port.mk>
