# $Id$
#
# BROKEN: expect (no package file yet)
# BROKEN: gnat (not really broken, just requires existing gnat compiler)
#

SUBDIR=	Gofer STk Sather elk forth g77 gcl guile-ii \
	icon itcl logo mit-scheme nTk p2c perl5 \
	scheme48 schemetoc scm smalltalk tcl tclX

.include <bsd.port.subdir.mk>
