# $Id$
#
# BROKEN: expect (no package file yet)
#

SUBDIR=	Gofer STk Sather elk forth g77 gcl gnat guile-ii \
	icon itcl logo mit-scheme nTk p2c perl5 \
	scheme48 schemetoc scm smalltalk tcl tclX

.include <bsd.port.subdir.mk>
