# New ports collection makefile for:    less
# Version required:     2.37
# Date created:         8 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       less-237
MASTER_SITES=   ftp://prep.ai.mit.edu/pub/gnu/
GNU_CONFIGURE=	YES

.include <bsd.port.mk>
