# New ports collection makefile for:    less
# Version required:     2.52
# Date created:         8 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       less-252
# Commented out, often busy
# MASTER_SITES=  ftp://prep.ai.mit.edu/pub/gnu/
# Mirror:
MASTER_SITES=   ftp://ftp.uu.net/systems/gnu/
GNU_CONFIGURE=	YES

.include <bsd.port.mk>
