# New ports collection makefile for:	screen
# Version required:     3.7.1
# Date created:         25 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       screen-3.7.1
CATEGORIES=	misc
MASTER_SITES=   ftp://ftp.uni-erlangen.de/pub/utilities/screen/

MAINTAINER=	ache@FreeBSD.ORG

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
