# New ports collection makefile for:	screen
# Version required:     3.5.17beta
# Date created:         25 Nov 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       screen-3.5.17beta
NCFTPFLAGS=     -PN
MASTER_SITES=   ftp://ftp.uni-erlangen.de/pub/utilities/screen/
GNU_CONFIGURE=	YES
WRKSRC=         ${WRKDIR}/screen-3.5.17

.include <bsd.port.mk>
