# New ports collection makefile for:	mule 2.3@19.34 with Wnn6
# Version required:	2.3@19.34
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	ja-mule-wnn6-2.3
CATEGORIES=	japanese editors

BROKEN_ELF=	yes

WNN6=		yes

.include "${.CURDIR}/../../editors/mule/Makefile"
