# New ports collection makefile for:	mule with Canna
# Version required:	2.3
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	jp-mule-canna-2.3
CATEGORIES=	japanese editors

CANNA=		yes

.include "${.CURDIR}/../../editors/mule/Makefile"
