# New ports collection makefile for:	bash
# Version required:     1.14.3
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       bash-1.14.3
MASTER_SITES=   ftp://slc2.ins.cwru.edu/pub/hidden/

.include <bsd.port.mk>
