# New ports collection makefile for:	bash
# Version required:     1.14.7
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       bash-1.14.7
CATEGORIES=	shells
MASTER_SITES=   ftp://slc2.ins.cwru.edu/pub/dist/

MAINTAINER=     ache@FreeBSD.ORG

NOMANCOMPRESS=	"Don't compress manpages or .so does not work."
MAN1=		bash.1 bash_builtins.1

.include <bsd.port.mk>
