# New ports collection makefile for:	gsm
# Version required:	gsm-1.0.7
# Date created:		5 January 1995
# Whom:			pst
#
# $Id$
#

DISTNAME=	gsm-1.0.7
CATEGORIES+=	audio
MASTER_SITES=	ftp://ftp.cs.tu-berlin.de/pub/local/kbs/tubmik/gsm/

WRKSRC=		${WRKDIR}/gsm-1.0-pl7

.include <bsd.port.mk>
