# New ports collection makefile for:	gsm
# Version required:	gsm-1.0.4
# Date created:		5 January 1995
# Whom:			pst
#
# $Id$
#

DISTNAME=	gsm-1.0.4
CATEGORIES+=	audio
MASTER_SITES=	ftp://gaia.cs.umass.edu/pub/hgschulz/nevot/
EXTRACT_SUFX=	.tar.Z

WRKSRC=		${WRKDIR}/gsm-1.0-pl4

.include <bsd.port.mk>
