# New ports collection makefile for:	pixmap
# Version required:	2.6
# Date created:		19 February 1995
# Whom:			jmz
#
# $Id$
#

DISTNAME=	pixmap2.6
PKGNAME=	pixmap-2.6
CATEGORIES+=	graphics
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/applications/pixmap/
MAINTAINER=	jmz@FreeBSD.org

LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

WRKSRC=		${WRKDIR}/pixmap
USE_IMAKE=	yes

.include <bsd.port.mk>
