# New ports collection makefile for:	pixmap
# Version required:	2.6
# Date created:		19 February 1995
# Whom:			jmz
#
# $Id$
#

USE_IMAKE=	yes
DISTNAME=	pixmap2.6
LIB_DEPENDS=	Xpm\\.4\\.:${PORTSDIR}/graphics/xpm
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/applications/pixmap/
CATEGORIES+=	graphics
WRKSRC=		${WRKDIR}/pixmap

.include <bsd.port.mk>
