# New ports collection makefile for:	xgraph
# Version required:	11
# Date created:		24 November 1994
# Whom:			asami
#
# $Id$
#

DISTNAME=	xgraph-11
USE_IMAKE=	yes
MASTER_SITES=	ftp://ftp.cs.orst.edu/pub/src/Xclients.local/
EXTRACT_SUFX=	.tar.Z

.include <bsd.port.mk>
