# New ports collection makefile for:	xgraph
# Version required:	11.3.2
# Date created:		24 November 1994
# Whom:			asami
#
# $Id$
#

DISTNAME=	xgraph-11.3.2
CATEGORIES=	math print
MASTER_SITES=	ftp://ftp.iis.u-tokyo.ac.jp/pub/X/misc/

MAINTAINER=	ports@FreeBSD.ORG

USE_IMAKE=	yes

.include <bsd.port.mk>
