# New ports collection makefile for:    xsol
# Version required:     2.1.1
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xsol-new
MASTER_SITES=	ftp://iraun1.ira.uka.de/pub/x11/games/
CATEGORIES+=	games
USE_IMAKE=      yes

.include <bsd.port.mk>
