# New ports collection makefile for:    ruby
# Version required:     1.0-971125
# Date created:         04 September 1997
# Whom:                 Eiji-usagi-MATSUmoto <usagi@ruby.club.or.jp>
#
# $Id$
#

DISTNAME=	ruby-1.0-971125
PKGNAME=	ruby-1.0
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.netlab.co.jp/pub/lang/ruby/

MAINTAINER=	usagi@ruby.club.or.jp

HAS_CONFIGURE=	yes

test:
	@(cd ${WRKSRC}; make test)

.include <bsd.port.mk>
