# New ports collection makefile for:	Blackbox
# Version required:	0.50.0
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $Id$
#

DISTNAME=	blackbox-0.50.0
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://balance.wiw.org/pub/blackbox/

MAINTAINER=	ports@FreeBSD.ORG

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
