# New ports collection makefile for:    unrar
# Version required:     1.00e
# Date created:         28 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       unrar100
PKGNAME=        unrar-1.00e
CATEGORIES+=	archivers
MASTER_SITES=   ftp://ftp.kiae.su/unix/arcers/
EXTRACT_SUFX=   .tgz

MAINTAINER=     ache@FreeBSD.ORG

WRKSRC=         ${WRKDIR}/unrar.100

.include <bsd.port.mk>
