# New ports collection makefile for:    unrar
# Version required:     1.00e
# Date created:         28 Dec 1994
# Whom:                 ache
#
# $Id$
#
DISTNAME=       unrar100
EXTRACT_SUFX=   .tgz
MASTER_SITES=   ftp://ftp.kiae.su/unix/arcers/
CATEGORIES+=	archivers
WRKSRC=         ${WRKDIR}/unrar.100

.include <bsd.port.mk>
