# New ports collection makefile for:    unrar
# Version required:     1.01
# Date created:         28 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       unrar101
PKGNAME=        unrar-1.01a
CATEGORIES+=	archivers
MASTER_SITES=   ftp://ftp.relcom.ru/unix/arcers/
PATCH_SITES=    $(MASTER_SITES)
PATCHFILES=     unrar101a.patch
EXTRACT_SUFX=   .tgz

MAINTAINER=     ache@FreeBSD.ORG

WRKSRC=         ${WRKDIR}/unrar.101

.include <bsd.port.mk>
