# New ports collection makefile for:    workman
# Version required:     1.3
# Date created:         25 Now 1995
# Whom:                 Donald Burr <d_burr@ix.netcom.com>
#
# $Id$
#

DISTNAME=       WorkMan-1.3
PKGNAME=	workman-1.3
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications/WorkMan

MAINTAINER=	d_burr@ix.netcom.com

LIB_DEPENDS=	xview\\.3\\.:${PORTSDIR}/x11/xview-lib

WRKSRC=		${WRKDIR}/workman
USE_IMAKE=	yes

.include <bsd.port.mk>
