# New ports collection makefile for:	X Font Server with X True Type
# Version required:	1.0
# Date created:		15 April 1998
# Whom:			Taguchi Takeshi <taguchi@tohoku.iij.ad.jp>
#
# $Id$
#

DISTNAME=	xc
PKGNAME=	xtt-xfs-1.0
CATEGORIES=	x11

MAINTAINER=	taguchi@tohoku.iij.ad.jp

SERVER=		xfs

.include "${.CURDIR}/../XttXF86srv-common/Makefile"
