# New ports collection makefile for:	sitecopy
# Version required:     0.4.*
# Date created:		15 January 1999
# Whom:			nik
#
# $Id$
#

DISTNAME=       sitecopy-0.4.8
CATEGORIES=	www
MASTER_SITES=   http://www.lyra.org/sitecopy/

MAINTAINER=     nik@FreeBSD.ORG

FETCH_BEFORE_ARGS=	-b
GNU_CONFIGURE=  yes
ALL_TARGET=     sitecopy

MAN1=		sitecopy.1

.include <bsd.port.mk>
