# $Id$
#

    SUBDIR += cpmemu
    SUBDIR += cpmtools
    SUBDIR += hfs
    SUBDIR += mtools
    SUBDIR += pcemu
    SUBDIR += sim6811
    SUBDIR += tkhfs
    SUBDIR += vmsbackup
    SUBDIR += wine

.include <bsd.port.subdir.mk>
