# $Id$
#

    SUBDIR += cpmemu
    SUBDIR += cpmtools
    SUBDIR += hfs
    SUBDIR += linux_lib
    SUBDIR += mtools
    SUBDIR += pcemu
    SUBDIR += sim6811
    SUBDIR += spim
    SUBDIR += tkhfs
    SUBDIR += vmsbackup
    SUBDIR += wine
    SUBDIR += x48

.include <bsd.port.subdir.mk>
