# New ports collection makefile for:    POV-Ray
# Version required:     2.2
# Date created:         28 Dec 1994
# Whom:                 jmacd@uclink.berkeley.edu
#
# $Id$
#

DISTNAME=       POV-Ray-2.2
MASTER_SITES=	ftp://povray.cdrom.com/pub/povray/Official/Generic-Unix/
DISTFILES=      povdoc.tar.Z povscn.tar.Z povsrc.tar.Z
EXTRACT_SUFX=	tar.Z
NO_WRKSUBDIR=


.include <bsd.port.mk>
