# New ports collection makefile for:	metamail
# Version required:	2.7
# Date created:		17 Oct 1994
# Whom:			torstenb
#
# $Id$
#

DISTNAME=	mm2.7
PKGNAME=	mm-2.7
CATEGORIES+=	mail
MASTER_SITES=	ftp://thumper.bellcore.com/pub/nsb/
EXTRACT_SUFX=	.tar.Z

WRKSRC=		${WRKDIR}/${DISTNAME}/src

.include <bsd.port.mk>
