# New ports collection makefile for:    xasteroids
# Version required:	5
# Date created:         3 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xpilot-3.3.1
PKGNAME=	xpilot
CATEGORIES+=	games
MASTER_SITES=	ftp://ftp.cs.uit.no/pub/games/xpilot/

USE_IMAKE=	yes
NO_INSTALL_MANPAGES= yes
WRKSRC=		${WRKDIR}/xpilot-3.3.1/src

.include <bsd.port.mk>
