# New ports collection makefile for:    xpilot
# Version required:	3-3-1
# Date created:         18 July 1995
# Whom:                 jmacd
#
# $Id$
#

DISTNAME=       xpilot-3.5.1
CATEGORIES+=	games
MASTER_SITES=	ftp://ftp.cs.uit.no/pub/games/xpilot/

USE_IMAKE=	yes

.include <bsd.port.mk>
