# New ports collection makefile for: YaTeX
# Version required:	1.66
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@infonets.hiroshima-u.ac.jp>
#
# $Id$
#

PKGNAME=	yatex-mule-1.66
CATEGORIES=	print elisp

MULE=		yes

MASTERDIR=	${.CURDIR}/../yatex
PLIST=		${.CURDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
