# New ports collection makefile for:    linux_lib
# Version required:	1.0
# Date created:         
# Whom:                 erich@FreeBSD.org
#
# $Id$
#

DISTNAME=	linux_lib
CATEGORIES=	emulators
MAINTAINER=	erich@FreeBSD.org

PREFIX=		/compat/linux/
WRKSRC=		${WRKDIR}

pre-build:
	@mkdir -p ${PREFIX}

.include <bsd.port.mk>
