# New ports collection makefile for:	xpermon++ V1.1
# Version required:	1.1
# Date created:		8 March 95
# Whom:			Lars Koeller <lars.koeller@odie.physik2.uni-rostock.de>
#
# $Id$
#

DISTNAME=	xperfmon++
USE_IMAKE=	yes
# In Germany try this
# MASTER_SITES=	ftp://odie.physik2.uni-rostock.de/pub/
CATEGORIES+=	x11
MASTER_SITES=	ftp://proteus.arc.nasa.gov/pub/
CATEGORIES+=	x11
DISTFILES=	xperfmon++v1.1.tar.Z
EXTRACT_ONLY=	xperfmon++v1.1.tar.Z

.include <bsd.port.mk>

