# $Id$
#

    SUBDIR += elm
    SUBDIR += elm+mime
    SUBDIR += elm+pgp+mime
    SUBDIR += metamail
    SUBDIR += mh
    SUBDIR += mpack
    SUBDIR += pgpsendmail
    SUBDIR += pine
    SUBDIR += popclient
    SUBDIR += popper
    SUBDIR += procmail
    SUBDIR += smail
    SUBDIR += xfmail

.include <bsd.port.subdir.mk>
