# $Id$
#

    SUBDIR += elm
    SUBDIR += exim
    SUBDIR += exmh
    SUBDIR += fetchmail
    SUBDIR += mailagent
    SUBDIR += majordomo
    SUBDIR += metamail
    SUBDIR += mh
    SUBDIR += mpack
    SUBDIR += pgpsendmail
    SUBDIR += pine
    SUBDIR += popclient
    SUBDIR += popper
    SUBDIR += procmail
    SUBDIR += smail
    SUBDIR += xfmail
    SUBDIR += youbin

.include <bsd.port.subdir.mk>
