# New ports collection makefile for: nwrite
# Version required:     1.0
# Date created:                29 July 1997
# Whom:                        daveh
#
# $Id$
#

DISTNAME=	nwrite-1.9.2
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.csua.berkeley.edu/pub/nwrite/

MAINTAINER=	daveh@csua.berkeley.edu

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--enable-clear-procs

MAN1=		nwrite.1

.include <bsd.port.mk>
