# New ports collection makefile for: d1489
# Version required:     1.2
# Date created:         1 May 1995
# Whom:                 ache
#
# $Id$
#

DISTNAME=       ru-d1489-1.2
CATEGORIES+=    russian utilities
MASTER_SITES=   ftp://ftp.kiae.su/unix/convert/char/
EXTRACT_SUFX=   .tgz

MAINTAINER=	ache@FreeBSD.ORG

.include <bsd.port.mk>
