# New ports collection makefile for:	hpscan
# Version required:	<own lineage>
# Date created:		12 January 1996
# Whom:			nate
#
# $Id$
#

DISTNAME=	scanner
PKGNAME=	hpscan
CATEGORIES+=	graphics
MASTER_SITES=	ftp://freefall.cdrom.com/pub/FreeBSD/LOCAL_PORTS/ \
		ftp://macbeth.cogsci.ed.ac.uk/pub/

NO_WRKSUBDIR=		true
USE_X11=		true
USE_IMAKE=		true
NO_INSTALL_MANPAGES=	true

MAINTAINER=	nate@FreeBSD.org

.include <bsd.port.mk>
