# New ports collection makefile for:    xmris
# Version required:     4.02
# Date created:         21 September 1994
# Whom:                 jmz
#
# $Id$

DISTNAME=	xmris.4.02
PKGNAME=	xmris-4.02
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/

MAINTAINER=	jmz@FreeBSD.org

USE_GMAKE=	yes
USE_IMAKE=      yes
MAKE_FLAGS=	XAPPLOADDIR=${PREFIX}/lib/X11/app-defaults -f

.include <bsd.port.mk>
