# New ports collection makefile for:	strobe
# Version required:	1.03
# Date created:		23 Sep 1996
# Whom:			proff
#
# $Id$
#

DISTNAME=	strobe-1.03
CATEGORIES=	net security
MASTER_SITES=	ftp://suburbia.net/pub/proff/original/strobe/

MAINTAINER=	proff@suburbia.net

WRKSRC=		${WRKDIR}/strobe
ALL_TARGET=	strobe
MAN1=		strobe.1

.include <bsd.port.mk>
