# $Id$
#

    SUBDIR += Wnn
    SUBDIR += c2t
    SUBDIR += celvis
    SUBDIR += cless
    SUBDIR += cxterm
    SUBDIR += gb2ps
    SUBDIR += gbscript
    SUBDIR += hc
    SUBDIR += lunar

.include <bsd.port.subdir.mk>
