# $Id$
#

    SUBDIR += Wnn
    SUBDIR += big5con
    SUBDIR += c2t
    SUBDIR += celvis
    SUBDIR += cless
    SUBDIR += cxterm
    SUBDIR += gb2ps
    SUBDIR += gbscript
    SUBDIR += hc
    SUBDIR += lunar
    SUBDIR += nvi-big5
    SUBDIR += nvi-euc-cn

.include <bsd.port.subdir.mk>
