# New ports collection makefile for:    hpack.with_encryption
# This program can't be imported/re-exported from USA
# Version required:     0.79a0
# Date created:         7 Jan 1995
# Whom:                 ache
#
# $Id$
#
DISTNAME=       hpack79src
EXTRACT_SUFX=   .tar.Z
MASTER_SITES=   ftp://src.doc.ic.ac.uk/packages/hpack/
NO_WRKSUBDIR=	yes
MAKEFILE=       makefile
ALL_TARGET=     freebsd
INSTALL_TARGET= freebsd.install

.include <bsd.port.mk>
