# $Id$
#

    SUBDIR += X.language
    SUBDIR += cyrproxy
    SUBDIR += d1489
    SUBDIR += elm.language
    SUBDIR += gd
    SUBDIR += netscape3.language
    SUBDIR += pgp.language
    SUBDIR += pine.language
    SUBDIR += rispell
    SUBDIR += wmcyrx
    SUBDIR += xruskb

.include <bsd.port.subdir.mk>
