# $Id$
#

    SUBDIR += d1489
    SUBDIR += X.language
    SUBDIR += elm.language
    SUBDIR += netscape2.language
    SUBDIR += netscape3.language
    SUBDIR += netscape3.01.language
    SUBDIR += pgp.language

.include <bsd.port.subdir.mk>
