#!/bin/sh
#
# $FreeBSD$

oopath=%%PREFIX%%/OpenOffice.org1.0/program/
program=`echo $0 | sed -e 's|.*-||'`

if [ ! $LANG ]; then
	export LANG=%%LANG%%
fi

case $program in
$0)
	exec $oopath/soffice "$@"
	;;
	*)
	exec $oopath/$program "$@"
	;;
esac
