# New ports collection makefile for:	Xaw3d
# Version required:	1.0
# Date created:		18 November 1994
# Whom:			asami
#
# $Id$
#

DISTNAME=	Xaw3d-1.0
USE_IMAKE=	yes
MASTER_SITES=	ftp://crl.dec.com/pub/X11/contrib/widgets/Xaw3d/R6/
MAINTAINER=	asami@FreeBSD.ORG
WRKSRC=		${WRKDIR}/lib/Xaw3d

.include <bsd.port.mk>
