# $Id$
#

    SUBDIR += autoconf
    SUBDIR += bcc
    SUBDIR += bison
    SUBDIR += cflow
    SUBDIR += dmake
    SUBDIR += gmake
    SUBDIR += gperf
    SUBDIR += libdlmalloc
    BROKEN += libmalloc
    SUBDIR += m4
    SUBDIR += mprof
    SUBDIR += noweb
    SUBDIR += xxgdb

.include <bsd.port.subdir.mk>
