# $Id$
#

    SUBDIR += SWIG
    SUBDIR += autoconf
    SUBDIR += bcc
    SUBDIR += bison
    SUBDIR += cflow
    SUBDIR += dmake
    SUBDIR += flex
    SUBDIR += gmake
    SUBDIR += gperf
    SUBDIR += libdlmalloc
    SUBDIR += libmalloc
    SUBDIR += libslang
    SUBDIR += libz
    SUBDIR += m4
    SUBDIR += mkmf
    SUBDIR += mprof
    SUBDIR += noweb
    SUBDIR += xxgdb

.include <bsd.port.subdir.mk>
