# New ports collection makefile for:	xfsm
# Version required:			1.97
# Date Created:				24 Nov 1997
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.ORG>
#
# $Id$
#

DISTNAME=	xfsm-1.97
CATEGORIES=	sysutils x11
MASTER_SITES=	http://www.peoplesoft.com/peoplepages/g/robert_gasch/src/
EXTRACT_SUFX=	.tgz

MAINTAINER=	vanilla@FreeBSD.ORG

USE_IMAKE=	yes

.include <bsd.port.mk>
