# New ports collection makefile for:    xpaint
# Version required:     2.1.1
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $Id$
#

DISTNAME=       xpaint-2.1.1
MASTER_SITES=	ftp://romulus.ucs.uoknor.edu/X/R5contrib
DEPENDS=	${PORTSDIR}/x11/jpeg ${PORTSDIR}/x11/tiff ${PORTSDIR}/x11/xpm
USE_IMAKE=      yes
INSTALL_MANPAGES=     yes
WRKSRC=		${.CURDIR}/work/xpaint

.include <bsd.port.mk>
