# $Id$
#

    SUBDIR += bpl+
    SUBDIR += ecu
    SUBDIR += hylafax
    SUBDIR += kermit
    SUBDIR += mgetty+sendfax
    SUBDIR += minicom
    SUBDIR += rzsz
    SUBDIR += seyon

.include <bsd.port.subdir.mk>
