# $Id$
#

    SUBDIR += bpl+
    SUBDIR += ecu
    SUBDIR += estic
    SUBDIR += hylafax
    SUBDIR += kermit
    SUBDIR += lrzsz
    SUBDIR += mgetty+sendfax
    SUBDIR += minicom
    SUBDIR += zmtx-zmrx
    SUBDIR += rzsz
    SUBDIR += seyon
    SUBDIR += xcept

.include <bsd.port.subdir.mk>
