# $Id$
#

    SUBDIR += bpl+
    SUBDIR += ecu
    SUBDIR += hylafax
    SUBDIR += kermit
    SUBDIR += lrzsz
    SUBDIR += mgetty+sendfax
    SUBDIR += minicom
    SUBDIR += qpage
    SUBDIR += rzsz
    SUBDIR += seyon
    SUBDIR += snooper
    SUBDIR += tkhylafax
    SUBDIR += xcept
    SUBDIR += zmtx-zmrx

.include <bsd.port.subdir.mk>
