# Ports collection makefile for:	xspringies
# Version required:			1.1
# Date created:				12 January 1997
# Whom:					jkh
#
# $Id$
#

DISTNAME=	xspringies-1.1
CATEGORIES=	games
MASTER_SITES=	http://aixpdslib.seas.ucla.edu/pub/xspringies/RISC/3.2/src/
DISTFILES=	xspringies.1.1.tar.Z

MAINTAINER=	jkh@FreeBSD.ORG

USE_IMAKE=	yes

.include <bsd.port.mk>
