# New ports collection makefile for:	xpdf
# Version required:     0.6
# Date created:         02 Feb 1996
# Whom:                 chuckr@glue.umd.edu
#
# $Id$
#

DISTNAME=       xpdf-0.6
CATEGORIES=	graphics
MASTER_SITES=   ftp://ftp.andrew.cmu.edu/pub/xpdf/

MAINTAINER=	chuckr@glue.umd.edu

USE_X11=	yes
MAN1=		xpdf.1 pdftops.1

.include <bsd.port.mk>
