# New ports collection makefile for:	buffer
# Version required:     1.17
# Date created:         17 Nov 1995
# Whom:                 markm
#
# $Id$
#

DISTNAME=       buffer-1.17
CATEGORIES=	misc
MASTER_SITES=   ftp://ftp.sun.ac.za/pub/unix/misc/

MAINTAINER=	markm@FreeBSD.ORG

NO_WRKSUBDIR=	yes
MANL=		buffer.l

.include <bsd.port.mk>
