# New ports collection makefile for:	bcc
# Date created:		26 March 1995
# Whom:			joerg
#
# $Id$
#

DISTNAME=	bcc
CATEGORIES+=	development programming languages
MAINTAINER=	joerg@FreeBSD.org

.include <bsd.port.mk>
