# New ports collection makefile for:   jafm
# Version required:		0.5
# Date created:                31 August 1998
# Whom:                        brett@peloton.physics.montana.edu
#
# $Id$
#

DISTNAME=	jafm-0.5
CATEGORIES=	x11-fm
MASTER_SITES=	http://www-personal.usyd.edu.au:/~rlittlew/jafm/

MAINTAINER=	brett@peloton.physics.montana.edu

BROKEN=		fetch

USE_QT=		yes
USE_GMAKE=	yes
ALL_TARGET=	jafm

MAN8=	jafm.8

.include <bsd.port.mk>
