# New ports collection makefile for:	GNU make
# Version required:     3.73
# Date created:		11 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       make-3.73
GNU_CONFIGURE=	yes
MASTER_SITES=   ftp://prep.ai.mit.edu/pub/gnu/ ftp://ftp.uu.net/systems/gnu/
CATEGORIES+=	development programming

.include <bsd.port.mk>
