# New ports collection makefile for:	GNU make
# Version required:     3.74
# Date created:		11 September 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       make-3.74
PKGNAME=        gmake-3.74
CATEGORIES+=	development programming
MASTER_SITES=   ftp://prep.ai.mit.edu/pub/gnu/ \
		ftp://ftp.uu.net/systems/gnu/

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
