# New ports collection makefile for:    lha
# Version required:     1.14C
# Date created:         26 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       lha-114c
PKGNAME=        lha-1.14c
CATEGORIES+=	archivers
MASTER_SITES=   ftp://ftp.leo.chubu.ac.jp/pub/tools/
EXTRACT_SUFX=   .tgz

MAINTAINER=     ache@FreeBSD.ORG

NO_CDROM=       yes # if distributed without network, author must be informed, see DESCR

.include <bsd.port.mk>
