# New ports collection makefile for:    lha
# Version required:     1.14C
# Date created:         26 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       lha-114c
PKGNAME=        lha-1.14c
CATEGORIES=	archivers
MASTER_SITES=   ftp://ftp.leo.chubu.ac.jp/pub/tools/
EXTRACT_SUFX=   .tgz

MAINTAINER=     ache@FreeBSD.ORG

MANLANG=	ja
MAN1=		lha.1

.include <bsd.port.mk>
