# New ports collection makefile for:    lha
# Version required:     1.01u
# Date created:         26 Dec 1994
# Whom:                 ache
#
# $Id$
#

DISTNAME=       lha101u
PKGNAME=        lha-1.01u
CATEGORIES+=	archivers
MASTER_SITES=	ftp://garbo.uwasa.fi/unix/arcers/
EXTRACT_SUFX=   .tar.Z

MAINTAINER=     ache@FreeBSD.ORG

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
