# New ports collection makefile for:	xmine(1)
# Version required:	1.0.3 / Athena
# Date created:		25 December 1994
# Whom:			joerg
#
# $Id$
#

DISTNAME=	xmine-1.0.3-Xaw
CATEGORIES+=	games
USE_IMAKE=      yes

LIB_DEPENDS=        Xaw3d\\.:${PORTSDIR}/x11/Xaw3d

.include <bsd.port.mk>
