# New ports collection makefile for:	xmine
# Version required:	1.0.3 / Athena
# Date created:		25 December 1994
# Whom:			joerg
#
# $Id$
#

DISTNAME=	xmine-1.0.3-Xaw
PKGNAME=	xmine-1.0.3
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	joerg@FreeBSD.org

LIB_DEPENDS=    Xaw3d\\.:${PORTSDIR}/x11-toolkits/Xaw3d

USE_IMAKE=      yes
MAN6=		xmine.6
MANCOMPRESSED=	no

.include <bsd.port.mk>
