# New ports collection makefile for:    dviselect
# Version required:     ?
# Date created:         12 October 1994
# Whom:                 jmz
#
# $Id$
#

DISTNAME=	dviselect
PKGNAME=	dviselect-1.3
CATEGORIES+=	print
MASTER_SITES=	ftp://ftp.cs.umn.edu/pub/latex/software/

MAINTAINER=	jmz@FreeBSD.org

pre-install:
	@mkdir -p ${PREFIX}/man/man1
	@mkdir -p ${PREFIX}/bin

.include <bsd.port.mk>
