# New ports collection makefile for: sattrack
# Version required:                  3.1.6
# Date created:                      6 Apr 1996
# Whom:                              Brent J. Nordquist <bjn@visi.com>
#
# $Id$
#

DISTNAME=          sattrack-3.1.6
CATEGORIES=        astro
MASTER_SITES=      http://ssl.berkeley.edu/isi_www/

MAINTAINER=        bjn@visi.com

WRKSRC=            ${WRKDIR}/SatTrack-3.1.6/src

post-install:
	@${CAT} ${PKGDIR}/MESSAGE

.include <bsd.port.mk>
