# New ports collection makefile for: sattrack
# Version required:                  3.1.4
# Date created:                      6 Apr 1996
# Whom:                              Brent J. Nordquist <bjn@visi.com>
#
# $Id$
#

DISTNAME=          sattrack-3.1.4
CATEGORIES=        astro
MASTER_SITES=      http://ssl.berkeley.edu/isi_www/

MAINTAINER=        bjn@visi.com

NO_CDROM=	   "No bundling with commercial product without author's concent"

WRKSRC=            ${WRKDIR}/SatTrack/src
MAKE_FLAGS=        PREFIX=${PREFIX} -f

.include <bsd.port.mk>
