# New ports collection makefile for:	xzx
# Version required:     2.8.0
# Date created:         13 Nov 1997
# Whom:                 Sheldon Hearn <axl@iafrica.com>
#
# $Id$
#

DISTNAME=	xzx-2.8.0
CATEGORIES=	emulators
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR= system/emulators/zx

MAINTAINER=	sheldonh@iafrica.com

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

MAN1=		xzx.1

.include <bsd.port.mk>
