# $Id$
#

    SUBDIR += asclock
    SUBDIR += asclock-xlib
    SUBDIR += astime
    SUBDIR += bclock
    SUBDIR += dclock
    SUBDIR += emiclock
    SUBDIR += eyeclock
    SUBDIR += mlclock
    SUBDIR += mouseclock
    SUBDIR += pclock
    SUBDIR += rclock
    SUBDIR += swisswatch
    SUBDIR += t3d
    SUBDIR += tclock
    SUBDIR += wmcalclock
    SUBDIR += wmdate
    SUBDIR += wmitime
    SUBDIR += wmtime
    SUBDIR += wmtz
    SUBDIR += xalarm
    SUBDIR += xdaliclock
    SUBDIR += xtimer
    SUBDIR += xtu

.include <bsd.port.subdir.mk>
