# $Id$
#

    SUBDIR += asclock
    SUBDIR += astime
    SUBDIR += bclock
    SUBDIR += dclock
    SUBDIR += emiclock
    SUBDIR += eyeclock
    SUBDIR += mlclock
    SUBDIR += mouseclock
    SUBDIR += rclock
    SUBDIR += swisswatch
    SUBDIR += t3d
    SUBDIR += tclock
    SUBDIR += wmcalclock
    SUBDIR += wmdate
    SUBDIR += wmitime
    SUBDIR += wmtime
    SUBDIR += xalarm
    SUBDIR += xdaliclock
    SUBDIR += xtimer

.include <bsd.port.subdir.mk>
