# New ports collection makefile for: Mew for Emacs
# Version required:	1.92.4
# Date created:		30 December 1996
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $Id$
#

PKGNAME=	mew-1.92.4

EMACS=		yes

DIRENTRY=	"* Mew: (mew):	Messaging in the Emacs World."
INFOFILE=	mew.info

.include "${.CURDIR}/../../mail/mew-common/Makefile"
