# $Id$
#

    SUBDIR += ephem
    SUBDIR += luna
    SUBDIR += saoimage
    SUBDIR += sattrack
    SUBDIR += stars
    SUBDIR += sunclock
    SUBDIR += xearth
    SUBDIR += xephem
    SUBDIR += xphoon
    SUBDIR += xtide

.include <bsd.port.subdir.mk>
