# $Id$
#

    SUBDIR += agrep
    SUBDIR += docbook
    SUBDIR += glimpse
    SUBDIR += isearch
    SUBDIR += iso8879
    SUBDIR += ispell
    SUBDIR += jade
    SUBDIR += mgdiff
    SUBDIR += pilot_makedoc
    SUBDIR += rman
    SUBDIR += sp
    SUBDIR += unroff

.include <bsd.port.subdir.mk>
