# $Id$
#

    SUBDIR += agrep
    SUBDIR += glimpse
    SUBDIR += isearch
    SUBDIR += ispell
    SUBDIR += mgdiff
    SUBDIR += rman
    SUBDIR += sp
    SUBDIR += unroff

.include <bsd.port.subdir.mk>
