# New ports collection makefile for:	bash
# Version required:     1.14.4
# Date created:		21 August 1994
# Whom:			jkh
#
# $Id$
#

DISTNAME=       bash-1.14.4
CATEGORIES+=	shells
MASTER_SITES=	ftp://freefall.cdrom.com/pub/FreeBSD/LOCAL_PORTS/

.include <bsd.port.mk>
