# $Id$
#

    SUBDIR += afio
    SUBDIR += manck
    SUBDIR += sudo
    SUBDIR += top
    SUBDIR += tua
    SUBDIR += xbatt
    SUBDIR += xdu
    SUBDIR += xperfmon
    SUBDIR += xsysstats

.include <bsd.port.subdir.mk>
