# $Id$
#
# RESTRICTED: ivs (crypto, export controlled)
# 
# BROKEN: dgd-lpmud
# BROKEN: slirp (upgraded)
# BROKEN: wais (for XFree3.x)
#

SUBDIR= archie cern_httpd cern_linemode chimera dgd fspclient gated \
	gn gopher imm irc ircII \
	lynx mirror moxftp ncftp2 nv \
	pcnfsd pidentd pmf samba scotty sup tclDP \
	tcp_wrapper tcpblast tintin++ tkWWW tkined vic \
	wu-ftpd wwwish xarchie xgopher yale-tftpd ytalk zircon

.include <bsd.port.subdir.mk>
