# $Id$
#
#
SUBDIR= archie cern_httpd chimera dgd dgd-lpmud fspclient gn gopher irc \
	ircII lynx ncftp2 \
	pcnfsd pidentd pmf sup tclDP tcp_wrapper tcpblast tkWWW tintin++ wais \
	wu-ftpd yale-tftpd

.include <bsd.port.subdir.mk>
