# $Id$
#
# XXX ncftp moved to core distribution
#
SUBDIR= archie cern_httpd chimera dgd fspclient gn irc ircII lynx ncftp2 \
	pcnfsd pmf sup tcpblast wu-ftpd tcp_wrapper

.include <bsd.port.subdir.mk>
