# New ports collection makefile for:	xcolors
# Version required:	R6 contrib
# Date created:		10 May 1995
# Whom:			asami
#
# $Id$
#

DISTNAME=	xcolors
PKGNAME=	xcolors-1.3
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.x.org/pub/R6untarred/contrib/programs/

MAINTAINER=	asami@FreeBSD.ORG

WRKSRC=		${WRKDIR}/xcolors
USE_IMAKE=	yes
IGNOREFILES=	${DISTFILES}

.include <bsd.port.mk>
