# New ports collection makefile for:	samba
# Version required:			1.9.11
# Date created:				11th Feb 1995
# Whom:					gpalmer
#
# $Id$
#

DISTNAME=	samba-1.9.11
MASTER_SITES=	ftp://nimbus.anu.edu.au/pub/tridge/samba/
CATEGORIES+=	networking
MAINTAINER=	gpalmer@FreeBSD.ORG

pre-install:
	@mkdir -p /usr/local/samba

.include <bsd.port.mk>
